local Z = require("TabMover_Data") -- Thanks to Aviarita for the idea of using metatable & Thanks to duk for telling me how to set/obtain color picker values properly.
local Enabled     = ui.new_checkbox   ("LUA", "A", "Enable Tab Mover")
local MultiSelect = ui.new_multiselect("LUA", "A", "Selected Tabs", "RageBot", "Anti-Aim", "Visuals", "Misc")
                
local function CopyRage()               
    Z.Stored_R_Enabled                      = (ui.get(Z.R_Enabled))                                         Z.Stored_R_RemoveSpread                      = (ui.get(Z.R_RemoveSpread))
    Z.Stored_R_TargetSelection              = (ui.get(Z.R_TargetSelection))                                 Z.Stored_R_RemoveRecoil                      = (ui.get(Z.R_RemoveRecoil))
    Z.Stored_R_TargetHitbox                 = (ui.get(Z.R_TargetHitbox))                                    Z.Stored_R_AccuracyBoost                     = (ui.get(Z.R_AccuracyBoost))
    Z.Stored_R_AvoidLimbs                   = (ui.get(Z.R_AvoidLimbs))                                      Z.Stored_R_AccuracyBoostOptions              = (ui.get(Z.R_AccuracyBoostOptions))
    Z.Stored_R_AvoidHead                    = (ui.get(Z.R_AvoidHead))                                       Z.Stored_R_QuickStop                         = (ui.get(Z.R_QuickStop))
    Z.Stored_R_MultiPoint                   = (ui.get(Z.R_MultiPoint))                                      Z.Stored_R_QuickStopEarly                    = (ui.get(Z.R_QuickStopEarly))
    Z.Stored_R_MultiPointScale              = (ui.get(Z.R_MultiPointScale))                                 Z.Stored_R_QuickStopInFire                   = (ui.get(Z.R_QuickStopInFire))
    Z.Stored_R_DynamicMultiPoint            = (ui.get(Z.R_DynamicMultiPoint))                               Z.Stored_R_QuickPeekAssist                   = (ui.get(Z.R_QuickPeekAssist))
    Z.Stored_R_StomachScale                 = (ui.get(Z.R_StomachScale))                                    Z.Stored_R_AntiAimCorrection                 = (ui.get(Z.R_AntiAimCorrection))
    Z.Stored_R_AutomaticFire                = (ui.get(Z.R_AutomaticFire))                                   Z.Stored_R_PreferBodyAim                     = (ui.get(Z.R_PreferBodyAim))
    Z.Stored_R_AutomaticPenetration         = (ui.get(Z.R_AutomaticPenetration))                            Z.Stored_R_DelayShotOnUnduck                 = (ui.get(Z.R_DelayShotOnUnduck))
    Z.Stored_R_SilentAim                    = (ui.get(Z.R_SilentAim))                                       Z.Stored_R_OverrideAwp                       = (ui.get(Z.R_OverrideAwp))
    Z.Stored_R_MinHitchance                 = (ui.get(Z.R_MinHitchance))                                    Z.Stored_R_AutomaticScope                    = (ui.get(Z.R_AutomaticScope))
    Z.Stored_R_MinDamage                    = (ui.get(Z.R_MinDamage))                                       Z.Stored_R_ReduceAimStep                     = (ui.get(Z.R_ReduceAimStep))
    Z.Stored_R_MaximumFov                   = (ui.get(Z.R_MaximumFov))                                      Z.Stored_R_LowFpsMitigations                 = (ui.get(Z.R_LowFpsMitigations))
    Z.Stored_R_LogMissesDueToSpread         = (ui.get(Z.R_LogMissesDueToSpread))                            Z.Stored_R_MpMode                            = (ui.get(MpMode))
end

local function PasteRage()
    ui.set(Z.R_Enabled, Z.Stored_R_Enabled)                                                                 ui.set(Z.R_RemoveSpread, Z.Stored_R_RemoveSpread)
    ui.set(Z.R_TargetSelection, Z.Stored_R_TargetSelection)                                                 ui.set(Z.R_RemoveRecoil, Z.Stored_R_RemoveRecoil)
    ui.set(Z.R_TargetHitbox, Z.Stored_R_TargetHitbox)                                                       ui.set(Z.R_AccuracyBoost, Z.Stored_R_AccuracyBoost)
    ui.set(Z.R_AvoidLimbs, Z.Stored_R_AvoidLimbs)                                                           ui.set(Z.R_AccuracyBoostOptions, Z.Stored_R_AccuracyBoostOptions)
    ui.set(Z.R_AvoidHead, Z.Stored_R_AvoidHead)                                                             ui.set(Z.R_QuickStop, Z.Stored_R_QuickStop)
    ui.set(Z.R_MultiPoint, Z.Stored_R_MultiPoint)                                                           ui.set(Z.R_QuickStopEarly, Z.Stored_R_QuickStopEarly)
    ui.set(Z.R_MultiPointScale, Z.Stored_R_MultiPointScale)                                                 ui.set(Z.R_QuickStopInFire, Z.Stored_R_QuickStopInFire)
    ui.set(Z.R_DynamicMultiPoint, Z.Stored_R_DynamicMultiPoint)                                             ui.set(Z.R_QuickPeekAssist, Z.Stored_R_QuickPeekAssist)
    ui.set(Z.R_StomachScale, Z.Stored_R_StomachScale)                                                       ui.set(Z.R_AntiAimCorrection, Z.Stored_R_AntiAimCorrection)
    ui.set(Z.R_AutomaticFire, Z.Stored_R_AutomaticFire)                                                     ui.set(Z.R_PreferBodyAim, Z.Stored_R_PreferBodyAim)
    ui.set(Z.R_AutomaticPenetration, Z.Stored_R_AutomaticPenetration)                                       ui.set(Z.R_DelayShotOnUnduck, Z.Stored_R_DelayShotOnUnduck)
    ui.set(Z.R_SilentAim, Z.Stored_R_SilentAim)                                                             ui.set(Z.R_OverrideAwp, Z.Stored_R_OverrideAwp)
    ui.set(Z.R_MinHitchance, Z.Stored_R_MinHitchance)                                                       ui.set(Z.R_AutomaticScope, Z.Stored_R_AutomaticScope)
    ui.set(Z.R_MinDamage, Z.Stored_R_MinDamage )                                                            ui.set(Z.R_ReduceAimStep, Z.Stored_R_ReduceAimStep)
    ui.set(Z.R_MaximumFov, Z.Stored_R_MaximumFov)                                                           ui.set(Z.R_LowFpsMitigations, Z.Stored_R_LowFpsMitigations)
    ui.set(Z.R_LogMissesDueToSpread, Z.Stored_R_LogMissesDueToSpread)                                       ui.set(MpMode, Z.Stored_R_MpMode)
end

local function CopyAA()
    Z.Stored_A_Pitch                        = (ui.get(Z.A_Pitch))                                           Z.Stored_A_Enabled                           = (ui.get(Z.A_Enabled))
    Z.Stored_A_YawBase                      = (ui.get(Z.A_YawBase))                                         Z.Stored_A_CustomizeTriggers                 = (ui.get(Z.A_CustomizeTriggers))
    Z.Stored_A_Yaw                          = (ui.get(Z.A_Yaw))                                             Z.Stored_A_Triggers                          = (ui.get(Z.A_Triggers))
    Z.Stored_A_YawJitter                    = (ui.get(Z.A_YawJitter))                                       Z.Stored_A_OnShotAntiAim                     = (ui.get(Z.A_OnShotAntiAim))
    Z.Stored_A_BodyYaw                      = (ui.get(Z.A_BodyYaw))                                         Z.Stored_A_Amount                            = (ui.get(Z.A_Amount))
    Z.Stored_A_FakeYawLimit                 = (ui.get(Z.A_FakeYawLimit))                                    Z.Stored_A_Variance                          = (ui.get(Z.A_Variance))
    Z.Stored_A_EdgeYaw                      = (ui.get(Z.A_EdgeYaw))                                         Z.Stored_A_Limit                             = (ui.get(Z.A_Limit))
    Z.Stored_A_EdgeFakeYawOffset            = (ui.get(Z.A_EdgeFakeYawOffset))                               Z.Stored_A_FakeLagWhileShooting              = (ui.get(Z.A_FakeLagWhileShooting))
    Z.Stored_A_FreeStanding                 = (ui.get(Z.A_FreeStanding))                                    Z.Stored_A_ResetOnBunnyHop                   = (ui.get(Z.A_ResetOnBunnyHop))
    Z.Stored_A_FreeStandingIgnoreDuck       = (ui.get(Z.A_FreeStandingIgnoreDuck))                          Z.Stored_A_SlowMotion                        = (ui.get(Z.A_SlowMotion))
    Z.Stored_A_Twist                        = (ui.get(Z.A_Twist))                                           Z.Stored_A_FixLegMovement                    = (ui.get(Z.A_FixLegMovement))
    Z.Stored_A_LowerBodyYaw                 = (ui.get(Z.A_LowerBodyYaw))                                    Z.Stored_A_InfiniteDuck                      = (ui.get(Z.A_InfiniteDuck))
    Z.Stored_A_YawJSlider                   = (ui.get(YawJSlider))                                          Z.Stored_A_BodyYSlider                       = (ui.get(BodyYSlider))
    Z.Stored_A_YawSlider                    = (ui.get(YawSlider))
end

local function PasteAA()
    ui.set(Z.A_Pitch, Z.Stored_A_Pitch)                                                                     ui.set(Z.A_Enabled, Z.Stored_A_Enabled)
    ui.set(Z.A_YawBase, Z.Stored_A_YawBase)                                                                 ui.set(Z.A_CustomizeTriggers, Z.Stored_A_CustomizeTriggers)
    ui.set(Z.A_Yaw, Z.Stored_A_Yaw)                                                                         ui.set(BodyYSlider, Z.Stored_A_BodyYSlider)
    ui.set(Z.A_YawJitter, Z.Stored_A_YawJitter)                                                             ui.set(Z.A_OnShotAntiAim, Z.Stored_A_OnShotAntiAim)
    ui.set(Z.A_BodyYaw, Z.Stored_A_BodyYaw)                                                                 ui.set(Z.A_Amount, Z.Stored_A_Amount)
    ui.set(Z.A_FakeYawLimit, Z.Stored_A_FakeYawLimit)                                                       ui.set(Z.A_Variance, Z.Stored_A_Variance)
    ui.set(Z.A_EdgeYaw, Z.Stored_A_EdgeYaw)                                                                 ui.set(Z.A_Limit, Z.Stored_A_Limit)
    ui.set(Z.A_EdgeFakeYawOffset, Z.Stored_A_EdgeFakeYawOffset)                                             ui.set(Z.A_FakeLagWhileShooting, Z.Stored_A_FakeLagWhileShooting)
    ui.set(Z.A_FreeStanding, Z.Stored_A_FreeStanding)                                                       ui.set(Z.A_ResetOnBunnyHop, Z.Stored_A_ResetOnBunnyHop)
    ui.set(Z.A_FreeStandingIgnoreDuck, Z.Stored_A_FreeStandingIgnoreDuck)                                   ui.set(Z.A_SlowMotion, Z.Stored_A_SlowMotion)
    ui.set(Z.A_Twist, Z.Stored_A_Twist)                                                                     ui.set(Z.A_FixLegMovement, Z.Stored_A_FixLegMovement)
    ui.set(Z.A_LowerBodyYaw, Z.Stored_A_LowerBodyYaw)                                                       ui.set(Z.A_InfiniteDuck, Z.Stored_A_InfiniteDuck)
    ui.set(YawJSlider, Z.Stored_A_YawJSlider)                                                               ui.set(YawSlider, Z.Stored_A_YawSlider)                                                              
    if ui.get(Z.A_CustomizeTriggers) then ui.set(Z.A_Triggers, Z.Stored_A_Triggers) end
end

local function CopyVisuals()
    Z.Stored_V_Teammates                    = (ui.get(Z.V_Teammates))                                       Z.Stored_V_Player                            = (ui.get(Z.V_Player))
    Z.Stored_V_Dormant                      = (ui.get(Z.V_Dormant))                                         Z.Stored_V_PBW                               = (ui.get(Z.V_PBW))
    Z.Stored_V_HealthBar                    = (ui.get(Z.V_HealthBar))                                       Z.Stored_V_ShowTeammates                     = (ui.get(Z.V_ShowTeammates))
    Z.Stored_V_Name                         = (ui.get(Z.V_Name))                                            Z.Stored_V_Hands                             = (ui.get(Z.V_Hands))
    Z.Stored_V_Flags                        = (ui.get(Z.V_Flags))                                           Z.Stored_V_DisableModelOcclusion             = (ui.get(Z.V_DisableModelOcclusion))
    Z.Stored_V_WeaponText                   = (ui.get(Z.V_WeaponText))                                      Z.Stored_V_Shadow                            = (ui.get(Z.V_Shadow))
    Z.Stored_V_WeaponIcon                   = (ui.get(Z.V_WeaponIcon))                                      Z.Stored_V_LocalFakeShadow                   = (ui.get(Z.V_LocalFakeShadow))
    Z.Stored_V_Ammo                         = (ui.get(Z.V_Ammo))                                            Z.Stored_V_Radar                             = (ui.get(Z.V_Radar))    
    Z.Stored_V_Distance                     = (ui.get(Z.V_Distance))                                        Z.Stored_V_DroppedWeapon                     = (ui.get(Z.V_DroppedWeapon))
    Z.Stored_V_Glow                         = (ui.get(Z.V_Glow))                                            Z.Stored_V_Grenades                          = (ui.get(Z.V_Grenades))
    Z.Stored_V_HitMarker                    = (ui.get(Z.V_HitMarker))                                       Z.Stored_V_InaccuracyOverlay                 = (ui.get(Z.V_InaccuracyOverlay))
    Z.Stored_V_HitMarkerSound               = (ui.get(Z.V_HitMarkerSound))                                  Z.Stored_V_RecoilOverlay                     = (ui.get(Z.V_RecoilOverlay))
    Z.Stored_V_VisualizeSounds              = (ui.get(Z.V_VisualizeSounds))                                 Z.Stored_V_Bomb                              = (ui.get(Z.V_Bomb))
    Z.Stored_V_LineOfSight                  = (ui.get(Z.V_LineOfSight))                                     Z.Stored_V_GrenadeTrajectory                 = (ui.get(Z.V_GrenadeTrajectory))
    Z.Stored_V_Money                        = (ui.get(Z.V_Money))                                           Z.Stored_V_GrenadeProximityWarning           = (ui.get(Z.V_GrenadeProximityWarning))
    Z.Stored_V_Skeleton                     = (ui.get(Z.V_Skeleton))                                        Z.Stored_V_Spectators                        = (ui.get(Z.V_Spectators))
    Z.Stored_V_OOFA                         = (ui.get(Z.V_OOFA))                                            Z.Stored_V_PenetrationReticle                = (ui.get(Z.V_PenetrationReticle))
    Z.Stored_V_RemoveFlash                  = (ui.get(Z.V_RemoveFlash))                                     Z.Stored_V_Hostages                          = (ui.get(Z.V_Hostages))
    Z.Stored_V_RemoveSmoke                  = (ui.get(Z.V_RemoveSmoke))                                     Z.Stored_V_SharedEsp                         = (ui.get(Z.V_SharedEsp))  
    Z.Stored_V_RemoveFog                    = (ui.get(Z.V_RemoveFog))                                       Z.Stored_V_SharedEspWithOtherTeam            = (ui.get(Z.V_SharedEspWithOtherTeam))
    Z.Stored_V_RemoveSkybox                 = (ui.get(Z.V_RemoveSkybox))                                    Z.Stored_V_RestrictSharedEspUpdates          = (ui.get(Z.V_RestrictSharedEspUpdates))
    Z.Stored_V_VisualRecoilAdjustment       = (ui.get(Z.V_VisualRecoilAdjustment))                          Z.Stored_V_UpgradeTablet                     = (ui.get(Z.V_UpgradeTablet))
    Z.Stored_V_TransparentWalls             = (ui.get(Z.V_TransparentWalls))                                Z.Stored_V_DangerZoneItems                   = (ui.get(Z.V_DangerZoneItems))
    Z.Stored_V_TransparentProps             = (ui.get(Z.V_TransparentProps))                                Z.Stored_V_DroneGun                          = (ui.get(Z.V_DroneGun))
    Z.Stored_V_BrightnessAdjustment         = (ui.get(Z.V_BrightnessAdjustment))                            Z.Stored_V_BlackHawk                         = (ui.get(Z.V_BlackHawk))
    Z.Stored_V_RemoveScope                  = (ui.get(Z.V_RemoveScope))                                     Z.Stored_V_Drone                             = (ui.get(Z.V_Drone))
    Z.Stored_V_InstantScope                 = (ui.get(Z.V_InstantScope))                                    Z.Stored_V_RandomCase                        = (ui.get(Z.V_RandomCase))
    Z.Stored_V_DisablePostProcessing        = (ui.get(Z.V_DisablePostProcessing))                           Z.Stored_V_ToolCase                          = (ui.get(Z.V_ToolCase))
    Z.Stored_V_ForceThirdPersonA            = (ui.get(Z.V_ForceThirdPersonA))                               Z.Stored_V_PistolCase                        = (ui.get(Z.V_PistolCase))
    Z.Stored_V_ForceThirdPersonD            = (ui.get(Z.V_ForceThirdPersonD))                               Z.Stored_V_ExplosiveCase                     = (ui.get(Z.V_ExplosiveCase))
    Z.Stored_V_DisableTeammates             = (ui.get(Z.V_DisableTeammates))                                Z.Stored_V_HeavyWeaponCase                   = (ui.get(Z.V_HeavyWeaponCase))
    Z.Stored_V_BulletTracers                = (ui.get(Z.V_BulletTracers))                                   Z.Stored_V_LightWeaponCase                   = (ui.get(Z.V_LightWeaponCase))
    Z.Stored_V_BulletImpacts                = (ui.get(Z.V_BulletImpacts))                                   Z.Stored_V_DuffleBag                         = (ui.get(Z.V_DuffleBag))
    Z.Stored_V_Jammer                       = (ui.get(Z.V_Jammer))                                          Z.Stored_V_Briefcase                         = (ui.get(Z.V_Briefcase))
    Z.Stored_V_Ammobox                      = (ui.get(Z.V_Ammobox))                                         Z.Stored_V_TabletUpgradeZone                 = (ui.get(Z.V_TabletUpgradeZone))
    Z.Stored_V_Armor                        = (ui.get(Z.V_Armor))                                           Z.Stored_V_TabletUpgradeDrone                = (ui.get(Z.V_TabletUpgradeDrone))
    Z.Stored_V_ParachutePack                = (ui.get(Z.V_ParachutePack))                                   Z.Stored_V_CashStack                         = (ui.get(Z.V_CashStack))
    Z.Stored_V_BoundingBox                  = (ui.get(Z.V_BoundingBox))                                     Z.Stored_V_DroppedWeaponAmmo                 = (ui.get(Z.V_DroppedWeaponAmmo))
    Z.Stored_V_Crosshair                    = (ui.get(Z.V_Crosshair))
    
    Z.Stored_Size           = ui.get(Size)    Z.Stored_Pos            = ui.get(Pos)     Z.Stored_Duration       = ui.get(Duration) Z.Stored_Typ1           = ui.get(Typ1)    Z.Stored_Typ2           = ui.get(Typ2)
    Z.R0,Z.B0,Z.G0,Z.A0     = ui.get(Color0)  Z.R1,Z.B1,Z.G1,Z.A1     = ui.get(Color1)  Z.R2,Z.B2,Z.G2,Z.A2     = ui.get(Color2)   Z.R3,Z.B3,Z.G3,Z.A3     = ui.get(Color3)  Z.R4,Z.B4,Z.G4,Z.A4     = ui.get(Color4)
    Z.R5,Z.B5,Z.G5,Z.A5     = ui.get(Color5)  Z.R6,Z.B6,Z.G6,Z.A6     = ui.get(Color6)  Z.R7,Z.B7,Z.G7,Z.A7     = ui.get(Color7)   Z.R8,Z.B8,Z.G8,Z.A8     = ui.get(Color8)  Z.R9,Z.B9,Z.G9,Z.A9     = ui.get(Color9)
    Z.R10,Z.B10,Z.G10,Z.A10 = ui.get(Color10) Z.R11,Z.B11,Z.G11,Z.A11 = ui.get(Color11) Z.R12,Z.B12,Z.G12,Z.A12 = ui.get(Color12)  Z.R13,Z.B13,Z.G13,Z.A13 = ui.get(Color13) Z.R14,Z.B14,Z.G14,Z.A14 = ui.get(Color14)
    Z.R15,Z.B15,Z.G15,Z.A15 = ui.get(Color15) Z.R16,Z.B16,Z.G16,Z.A16 = ui.get(Color16) Z.R17,Z.B17,Z.G17,Z.A17 = ui.get(Color17)  Z.R18,Z.B18,Z.G18,Z.A18 = ui.get(Color18) Z.R19,Z.B19,Z.G19,Z.A19 = ui.get(Color19)
    Z.R20,Z.B20,Z.G20,Z.A20 = ui.get(Color20) Z.R21,Z.B21,Z.G21,Z.A21 = ui.get(Color21) Z.R22,Z.B22,Z.G22,Z.A22 = ui.get(Color22)  Z.R23,Z.B23,Z.G23,Z.A23 = ui.get(Color23) Z.R24,Z.B24,Z.G24,Z.A24 = ui.get(Color24)
    Z.R25,Z.B25,Z.G25,Z.A25 = ui.get(Color25) Z.R26,Z.B26,Z.G26,Z.A26 = ui.get(Color26) Z.R27,Z.B27,Z.G27,Z.A27 = ui.get(Color27)  Z.R28,Z.B28,Z.G28,Z.A28 = ui.get(Color28) Z.R29,Z.B29,Z.G29,Z.A29 = ui.get(Color29)
    Z.R30,Z.B30,Z.G30,Z.A30 = ui.get(Color30) Z.R31,Z.B31,Z.G31,Z.A31 = ui.get(Color31) Z.R32,Z.B32,Z.G32,Z.A32 = ui.get(Color32)  Z.R33,Z.B33,Z.G33,Z.A33 = ui.get(Color33) Z.R34,Z.B34,Z.G34,Z.A34 = ui.get(Color34)
    Z.R35,Z.B35,Z.G35,Z.A35 = ui.get(Color35) Z.R36,Z.B36,Z.G36,Z.A36 = ui.get(Color36) Z.R37,Z.B37,Z.G37,Z.A37 = ui.get(Color37)  Z.R38,Z.B38,Z.G38,Z.A38 = ui.get(Color38) Z.R39,Z.B39,Z.G39,Z.A39 = ui.get(Color39)
    Z.R40,Z.B40,Z.G40,Z.A40 = ui.get(Color40) Z.R41,Z.B41,Z.G41,Z.A41 = ui.get(Color41)
end

local function PasteVisuals()
    ui.set(Z.V_Teammates, Z.Stored_V_Teammates)                                                             ui.set(Z.V_Player, Z.Stored_V_Player)
    ui.set(Z.V_Dormant, Z.Stored_V_Dormant)                                                                 ui.set(Z.V_PBW, Z.Stored_V_PBW)
    ui.set(Z.V_HealthBar, Z.Stored_V_HealthBar)                                                             ui.set(Z.V_ShowTeammates, Z.Stored_V_ShowTeammates)
    ui.set(Z.V_Name, Z.Stored_V_Name)                                                                       ui.set(Z.V_Hands, Z.Stored_V_Hands)
    ui.set(Z.V_Flags, Z.Stored_V_Flags)                                                                     ui.set(Z.V_DisableModelOcclusion, Z.Stored_V_DisableModelOcclusion)
    ui.set(Z.V_WeaponText, Z.Stored_V_WeaponText)                                                           ui.set(Z.V_Shadow, Z.Stored_V_Shadow)
    ui.set(Z.V_WeaponIcon, Z.Stored_V_WeaponIcon)                                                           ui.set(Z.V_LocalFakeShadow, Z.Stored_V_LocalFakeShadow)
    ui.set(Z.V_Ammo, Z.Stored_V_Ammo)                                                                       ui.set(Z.V_Radar, Z.Stored_V_Radar)    
    ui.set(Z.V_Distance, Z.Stored_V_Distance)                                                               ui.set(Z.V_DroppedWeapon, Z.Stored_V_DroppedWeapon)
    ui.set(Z.V_Glow, Z.Stored_V_Glow)                                                                       ui.set(Z.V_Grenades, Z.Stored_V_Grenades)
    ui.set(Z.V_HitMarker, Z.Stored_V_HitMarker)                                                             ui.set(Z.V_InaccuracyOverlay, Z.Stored_V_InaccuracyOverlay)
    ui.set(Z.V_HitMarkerSound, Z.Stored_V_HitMarkerSound)                                                   ui.set(Z.V_RecoilOverlay, Z.Stored_V_RecoilOverlay)
    ui.set(Z.V_VisualizeSounds, Z.Stored_V_VisualizeSounds)                                                 ui.set(Z.V_Bomb, Z.Stored_V_Bomb)
    ui.set(Z.V_LineOfSight, Z.Stored_V_LineOfSight)                                                         ui.set(Z.V_GrenadeTrajectory, Z.Stored_V_GrenadeTrajectory)
    ui.set(Z.V_Money, Z.Stored_V_Money)                                                                     ui.set(Z.V_GrenadeProximityWarning, Z.Stored_V_GrenadeProximityWarning) 
    ui.set(Z.V_Skeleton, Z.Stored_V_Skeleton)                                                               ui.set(Z.V_Spectators, Z.Stored_V_Spectators)
    ui.set(Z.V_OOFA, Z.Stored_V_OOFA)                                                                       ui.set(Z.V_PenetrationReticle, Z.Stored_V_PenetrationReticle)
    ui.set(Z.V_RemoveFlash, Z.Stored_V_RemoveFlash)                                                         ui.set(Z.V_Hostages, Z.Stored_V_Hostages)
    ui.set(Z.V_RemoveSmoke, Z.Stored_V_RemoveSmoke)                                                         ui.set(Z.V_SharedEsp, Z.Stored_V_SharedEsp)  
    ui.set(Z.V_RemoveFog, Z.Stored_V_RemoveFog)                                                             ui.set(Z.V_SharedEspWithOtherTeam, Z.Stored_V_SharedEspWithOtherTeam)
    ui.set(Z.V_RemoveSkybox, Z.Stored_V_RemoveSkybox)                                                       ui.set(Z.V_RestrictSharedEspUpdates, Z.Stored_V_RestrictSharedEspUpdates)
    ui.set(Z.V_VisualRecoilAdjustment, Z.Stored_V_VisualRecoilAdjustment)                                   ui.set(Z.V_UpgradeTablet, Z.Stored_V_UpgradeTablet)
    ui.set(Z.V_TransparentWalls, Z.Stored_V_TransparentWalls)                                               ui.set(Z.V_DangerZoneItems, Z.Stored_V_DangerZoneItems)
    ui.set(Z.V_TransparentProps, Z.Stored_V_TransparentProps)                                               ui.set(Z.V_DroneGun, Z.Stored_V_DroneGun)
    ui.set(Z.V_BrightnessAdjustment, Z.Stored_V_BrightnessAdjustment)                                       ui.set(Z.V_BlackHawk, Z.Stored_V_BlackHawk)
    ui.set(Z.V_RemoveScope, Z.Stored_V_RemoveScope)                                                         ui.set(Z.V_Drone, Z.Stored_V_Drone)
    ui.set(Z.V_InstantScope, Z.Stored_V_InstantScope)                                                       ui.set(Z.V_RandomCase, Z.Stored_V_RandomCase)
    ui.set(Z.V_DisablePostProcessing, Z.Stored_V_DisablePostProcessing)                                     ui.set(Z.V_ToolCase, Z.Stored_V_ToolCase)
    ui.set(Z.V_ForceThirdPersonA, Z.Stored_V_ForceThirdPersonA)                                             ui.set(Z.V_PistolCase ,Z.Stored_V_PistolCase)
    ui.set(Z.V_ForceThirdPersonD, Z.Stored_V_ForceThirdPersonD)                                             ui.set(Z.V_ExplosiveCase, Z.Stored_V_ExplosiveCase)
    ui.set(Z.V_DisableTeammates, Z.Stored_V_DisableTeammates)                                               ui.set(Z.V_HeavyWeaponCase, Z.Stored_V_HeavyWeaponCase)
    ui.set(Z.V_BulletTracers, Z.Stored_V_BulletTracers)                                                     ui.set(Z.V_LightWeaponCase, Z.Stored_V_LightWeaponCase)
    ui.set(Z.V_BulletImpacts, Z.Stored_V_BulletImpacts)                                                     ui.set(Z.V_DuffleBag, Z.Stored_V_DuffleBag)
    ui.set(Z.V_Jammer, Z.Stored_V_Jammer)                                                                   ui.set(Z.V_Briefcase, Z.Stored_V_Briefcase)
    ui.set(Z.V_Ammobox, Z.Stored_V_Ammobox)                                                                 ui.set(Z.V_TabletUpgradeZone, Z.Stored_V_TabletUpgradeZone)
    ui.set(Z.V_Armor, Z.Stored_V_Armor)                                                                     ui.set(Z.V_TabletUpgradeDrone, Z.Stored_V_TabletUpgradeDrone)
    ui.set(Z.V_ParachutePack, Z.Stored_V_ParachutePack)                                                     ui.set(Z.V_CashStack, Z.Stored_V_CashStack)
    ui.set(Z.V_BoundingBox, Z.Stored_V_BoundingBox)                                                         ui.set(Z.V_Crosshair, Z.Stored_V_Crosshair)
    ui.set(Z.V_DroppedWeaponAmmo, Z.Stored_V_DroppedWeaponAmmo)
    
    ui.set(Size,    Z.Stored_Size)           ui.set(Pos,     Z.Stored_Pos)            ui.set(Duration, Z.Stored_Duration)       ui.set(Typ1,    Z.Stored_Typ1)           ui.set(Typ2,  Z.Stored_Typ2)       
    ui.set(Color0,  Z.R0,Z.B0,Z.G0,Z.A0)     ui.set(Color1,  Z.R1,Z.B1,Z.G1,Z.A1)     ui.set(Color2,   Z.R2,Z.B2,Z.G2,Z.A2)     ui.set(Color3,  Z.R3,Z.B3,Z.G3,Z.A3)     ui.set(Color4, Z.R4,Z.B4,Z.G4,Z.A4)   
    ui.set(Color5,  Z.R5,Z.B5,Z.G5,Z.A5)     ui.set(Color6,  Z.R6,Z.B6,Z.G6,Z.A6)     ui.set(Color7,   Z.R7,Z.B7,Z.G7,Z.A7)     ui.set(Color8,  Z.R8,Z.B8,Z.G8,Z.A8)     ui.set(Color9, Z.R9,Z.B9,Z.G9,Z.A9)   
    ui.set(Color10, Z.R10,Z.B10,Z.G10,Z.A10) ui.set(Color11, Z.R11,Z.B11,Z.G11,Z.A11) ui.set(Color12,  Z.R12,Z.B12,Z.G12,Z.A12) ui.set(Color13, Z.R13,Z.B13,Z.G13,Z.A13) ui.set(Color14, Z.R14,Z.B14,Z.G14,Z.A14)
    ui.set(Color15, Z.R15,Z.B15,Z.G15,Z.A15) ui.set(Color16, Z.R16,Z.B16,Z.G16,Z.A16) ui.set(Color17,  Z.R17,Z.B17,Z.G17,Z.A17) ui.set(Color18, Z.R18,Z.B18,Z.G18,Z.A18) ui.set(Color19, Z.R19,Z.B19,Z.G19,Z.A19)
    ui.set(Color20, Z.R20,Z.B20,Z.G20,Z.A20) ui.set(Color21, Z.R21,Z.B21,Z.G21,Z.A21) ui.set(Color22,  Z.R22,Z.B22,Z.G22,Z.A22) ui.set(Color23, Z.R23,Z.B23,Z.G23,Z.A23) ui.set(Color24, Z.R24,Z.B24,Z.G24,Z.A24)
    ui.set(Color25, Z.R25,Z.B25,Z.G25,Z.A25) ui.set(Color26, Z.R26,Z.B26,Z.G26,Z.A26) ui.set(Color27,  Z.R27,Z.B27,Z.G27,Z.A27) ui.set(Color28, Z.R28,Z.B28,Z.G28,Z.A28) ui.set(Color29, Z.R29,Z.B29,Z.G29,Z.A29)
    ui.set(Color30, Z.R30,Z.B30,Z.G30,Z.A30) ui.set(Color31, Z.R31,Z.B31,Z.G31,Z.A31) ui.set(Color32,  Z.R32,Z.B32,Z.G32,Z.A32) ui.set(Color33, Z.R33,Z.B33,Z.G33,Z.A33) ui.set(Color34, Z.R34,Z.B34,Z.G34,Z.A34)
    ui.set(Color35, Z.R35,Z.B35,Z.G35,Z.A35) ui.set(Color36, Z.R36,Z.B36,Z.G36,Z.A36) ui.set(Color37,  Z.R37,Z.B37,Z.G37,Z.A37) ui.set(Color38, Z.R38,Z.B38,Z.G38,Z.A38) ui.set(Color39, Z.R39,Z.B39,Z.G39,Z.A39)
    ui.set(Color40, Z.R40,Z.B40,Z.G40,Z.A40) ui.set(Color41, Z.R41,Z.B41,Z.G41,Z.A41)
end

local function CopyMisc()
    Z.Stored_M_OverrideFov                  = ui.get(Z.M_OverrideFov)                                                      Z.Stored_M_AutomaticWeapons         = ui.get(Z.M_AutomaticWeapons)
    Z.Stored_M_BunnyHop                     = ui.get(Z.M_BunnyHop)                                                         Z.Stored_M_JumpAtEdge               = ui.get(Z.M_JumpAtEdge)
    Z.Stored_M_AirStrafe                    = ui.get(Z.M_AirStrafe)                                                        Z.Stored_M_RevealCompetitveRanks    = ui.get(Z.M_RevealCompetitiveRanks)
    Z.Stored_M_AirStrafeDirection           = ui.get(Z.M_AirStrafeDirection)                                               Z.Stored_M_AutoAcceptMatchmaking    = ui.get(Z.M_AutoAcceptMatchmaking)
    Z.Stored_M_AirStrafeSmoothing           = ui.get(Z.M_AirStrafeSmoothing)                                               Z.Stored_M_AutomaticGrenadeRelease  = ui.get(Z.M_AutomaticGrenadeRelease)
    Z.Stored_M_Zhop                         = ui.get(Z.M_Zhop)                                                             Z.Stored_M_PingSpike                = ui.get(Z.M_PingSpike)
    Z.Stored_M_PreSpeed                     = ui.get(Z.M_PreSpeed)                                                         Z.Stored_M_FastWalk                 = ui.get(Z.M_FastWalk)
    Z.Stored_M_AirDuck                      = ui.get(Z.M_AirDuck)                                                          Z.Stored_M_PersistentKillFeed       = ui.get(Z.M_PersistentKillFeed)   
    Z.Stored_M_KnifeBot                     = ui.get(Z.M_KnifeBot)                                                         Z.Stored_M_AntiUntrusted            = ui.get(Z.M_AntiUntrusted) 
    Z.Stored_M_ZeusBot                      = ui.get(Z.M_ZeusBot)                                                          Z.Stored_M_HideFromObs              = ui.get(Z.M_HideFromObs)
    Z.Stored_M_BlockBot                     = ui.get(Z.M_BlockBot)                                                         Z.Stored_M_LowFpsWarning            = ui.get(Z.M_LowFpsWarning)
    Z.Stored_M_LockMenuLayout               = ui.get(Z.M_LockMenuLayout)                                                   Z.Stored_M_KnifeMode                = ui.get(KnifeMode)
    Z.Stored_M_Zy                           = ui.get(Zy)                                                                   Z.Stored_M_Zx                       = ui.get(Zx)
    Z.Stored_M_ADelay                       = ui.get(ADelay)                                                               Z.Stored_M_PingVal                  = ui.get(PingVal)
    Z.Stored_M_ClanTagSpammer               = ui.get(Z.M_ClanTagSpammer)                                                   Z.Stored_M_LogDamageDealt           = ui.get(Z.M_LogDamageDealt)
    Z.Stored_M_LogPurchases                 = ui.get(Z.M_LogPurchases)
end

local function PasteMisc()
    ui.set(Z.M_OverrideFov, Z.Stored_M_OverrideFov)                                                                       ui.set(Z.M_AutomaticWeapons, Z.Stored_M_AutomaticWeapons)       
    ui.set(Z.M_BunnyHop, Z.Stored_M_BunnyHop)                                                                             ui.set(Z.M_JumpAtEdge, Z.Stored_M_JumpAtEdge)    
    ui.set(Z.M_AirStrafe, Z.Stored_M_AirStrafe)                                                                           ui.set(Z.M_RevealCompetitiveRanks, Z.Stored_M_RevealCompetitveRanks)       
    ui.set(Z.M_AirStrafeDirection, Z.Stored_M_AirStrafeDirection)                                                         ui.set(Z.M_AutoAcceptMatchmaking, Z.Stored_M_AutoAcceptMatchmaking)    
    ui.set(Z.M_AirStrafeSmoothing, Z.Stored_M_AirStrafeSmoothing)                                                         ui.set(Z.M_AutomaticGrenadeRelease, Z.Stored_M_AutomaticGrenadeRelease)         
    ui.set(Z.M_Zhop, Z.Stored_M_Zhop)                                                                                     ui.set(Z.M_PingSpike, Z.Stored_M_PingSpike)       
    ui.set(Z.M_PreSpeed, Z.Stored_M_PreSpeed)                                                                             ui.set(Z.M_FastWalk, Z.Stored_M_FastWalk)        
    ui.set(Z.M_AirDuck, Z.Stored_M_AirDuck)                                                                               ui.set(Z.M_PersistentKillFeed, Z.Stored_M_PersistentKillFeed)        
    ui.set(Z.M_KnifeBot, Z.Stored_M_KnifeBot)                                                                             ui.set(Z.M_AntiUntrusted, Z.Stored_M_AntiUntrusted)       
    ui.set(Z.M_ZeusBot, Z.Stored_M_ZeusBot)                                                                               ui.set(Z.M_HideFromObs, Z.Stored_M_HideFromObs)     
    ui.set(Z.M_BlockBot, Z.Stored_M_BlockBot)                                                                             ui.set(Z.M_LowFpsWarning, Z.Stored_M_LowFpsWarning)         
    ui.set(Z.M_LockMenuLayout, Z.Stored_M_LockMenuLayout)                                                                 ui.set(KnifeMode, Z.Stored_M_KnifeMode)   
    ui.set(Zy, Z.Stored_M_Zy)                                                                                             ui.set(Zx, Z.Stored_M_Zx)          
    ui.set(ADelay, Z.Stored_M_ADelay)                                                                                     ui.set(PingVal, Z.Stored_M_PingVal)
    ui.set(Z.M_ClanTagSpammer, Z.Stored_M_ClanTagSpammer)                                                                 ui.set(Z.M_LogDamageDealt, Z.Stored_M_LogDamageDealt)
    ui.set(Z.M_LogPurchases, Z.Stored_M_LogPurchases)
    
end    

local function Copy()
    local SelectedTabs = ui.get(MultiSelect)
    for i=1, #SelectedTabs do
    if SelectedTabs[i] == "RageBot"  then CopyRage()    print("Copied RageBot Tab.")  end
    if SelectedTabs[i] == "Anti-Aim" then CopyAA()      print("Copied Anti-Aim Tab.") end
    if SelectedTabs[i] == "Visuals"  then CopyVisuals() print("Copied Visuals Tab.")  end
    if SelectedTabs[i] == "Misc"     then CopyMisc()    print("Copied Misc Tab.")     end
        end
end
        
local function Paste()
    local SelectedTabs = ui.get(MultiSelect)
    for i=1, #SelectedTabs do
    if SelectedTabs[i] == "RageBot"  then PasteRage()    print("Pasted RageBot Tab.")  end
    if SelectedTabs[i] == "Anti-Aim" then PasteAA()      print("Pasted Anti-Aim Tab.") end
    if SelectedTabs[i] == "Visuals"  then PasteVisuals() print("Pasted Visuals Tab.")  end
    if SelectedTabs[i] == "Misc"     then PasteMisc()    print("Pasted Misc Tab.")     end
        end
end    

local CopyButton   = ui.new_button("LUA", "A", "Copy Selected Tabs", Copy)
local PasteButton  = ui.new_button("LUA", "A", "Paste Selected Tabs", Paste)
local Ref1         = ui.reference ("LUA", "A", "Copy Selected Tabs")
local Ref2         = ui.reference ("LUA", "A", "Paste Selected Tabs")

local function HandleMenu()
    if ui.get(Enabled) then
        ui.set_visible(MultiSelect, true)
        ui.set_visible(Ref1, true)
        ui.set_visible(Ref2, true)
    else
        ui.set_visible(MultiSelect, false)
        ui.set (MultiSelect, "-")
        ui.set_visible(Ref1, false)
        ui.set_visible(Ref2, false)
        end
    end
HandleMenu()
ui.set_callback(Enabled, HandleMenu)