local Z_mt = {} -- Thanks to Aviarita for the idea of using metatable & Thanks to duk for telling me how to set/obtain color picker values properly.
--------------------------------------------------------------------------------------------------------------RAGE------------------------------------------------------------------------------------------------------
Z_mt.R_Enabled                             = ui.reference("RAGE", "Aimbot", "Enabled")                             Z_mt.R_AutomaticScope                 = ui.reference("RAGE", "Aimbot", "Automatic scope")
Z_mt.R_TargetSelection                     = ui.reference("RAGE", "Aimbot", "Target selection")                    Z_mt.R_ReduceAimStep                  = ui.reference("RAGE", "Aimbot", "Reduce aim step")
Z_mt.R_TargetHitbox                        = ui.reference("RAGE", "Aimbot", "Target hitbox")                       Z_mt.R_LogMissesDueToSpread           = ui.reference("RAGE", "Aimbot", "Log misses due to spread")
Z_mt.R_AvoidLimbs                          = ui.reference("RAGE", "Aimbot", "Avoid limbs if moving")               Z_mt.R_MaximumFov                     = ui.reference("RAGE", "Aimbot", "Maximum FOV")
Z_mt.R_AvoidHead                           = ui.reference("RAGE", "Aimbot", "Avoid head if jumping")               Z_mt.R_QuickStop                      = ui.reference("RAGE", "Other", "Quick stop")
Z_mt.R_MultiPoint, zz, MpMode              = ui.reference("RAGE", "Aimbot", "Multi-point")                         Z_mt.R_QuickStopOptions               = ui.reference("RAGE", "Other", "Quick stop options")
Z_mt.R_MultiPointScale                     = ui.reference("RAGE", "Aimbot", "Multi-point scale")                   Z_mt.R_PreferBodyAim                  = ui.reference("RAGE", "Other", "Prefer body aim")
Z_mt.R_DynamicMultiPoint                   = ui.reference("RAGE", "Aimbot", "Dynamic multi-point")                 Z_mt.R_AccuracyBoost                  = ui.reference("RAGE", "Other", "Accuracy boost")
Z_mt.R_SafePoint                           = ui.reference("RAGE", "Aimbot", "Prefer Safe point")                   Z_mt.R_AntiAimCorrection              = ui.reference("RAGE", "Other", "Anti-Aim correction")
Z_mt.R_LowFpsMitigations                   = ui.reference("RAGE", "Aimbot", "Low FPS mitigations")                 Z_mt.R_RemoveRecoil                   = ui.reference("RAGE", "Other", "Remove recoil")
Z_mt.R_AutomaticFire                       = ui.reference("RAGE", "Aimbot", "Automatic fire")                      Z_mt.R_PreferBodyAimDisablers         = ui.reference("RAGE", "Other", "Prefer body aim disablers")
Z_mt.R_AutomaticPenetration                = ui.reference("RAGE", "Aimbot", "Automatic penetration")               Z_mt.R_DelayShotOnUnduck              = ui.reference("RAGE", "Other", "Delay shot on unduck")
Z_mt.R_SilentAim                           = ui.reference("RAGE", "Aimbot", "Silent aim")                          Z_mt.R_DelayShotOnPeek                = ui.reference("RAGE", "Other", "Delay shot on peek")
Z_mt.R_MinHitchance                        = ui.reference("RAGE", "Aimbot", "Minimum hit chance")                  Z_mt.R_DoubleTap                      = ui.reference("RAGE", "Other", "Double tap")
Z_mt.R_MinDamage                           = ui.reference("RAGE", "Aimbot", "Minimum Damage")                      Z_mt.R_DoubleTapMode                  = ui.reference("RAGE", "Other", "Double tap mode")
Z_mt.R_OverrideAwp                         = ui.reference("RAGE", "Aimbot", "Override AWP")                        Z_mt.R_RemoveSpread                   = ui.reference("RAGE", "Other", "Remove spread")

--------------------------------------------------------------------------------------------------------------STORED RAGE-----------------------------------------------------------------------------------------------
Z_mt.SR_Enabled                            = (nil)                                                                 Z_mt.SR_RemoveSpread                  = (nil)
Z_mt.SR_TargetSelection                    = (nil)                                                                 Z_mt.SR_RemoveRecoil                  = (nil)
Z_mt.SR_TargetHitbox                       = (nil)                                                                 Z_mt.SR_AccuracyBoost                 = (nil)
Z_mt.SR_AvoidLimbs                         = (nil)                                                                 Z_mt.SR_ReduceAimStep                 = (nil)
Z_mt.SR_AvoidHead                          = (nil)                                                                 Z_mt.SR_QuickStop                     = (nil)
Z_mt.SR_MultiPoint                         = (nil)                                                                 Z_mt.SR_QuickStopOptions              = (nil)
Z_mt.SR_MultiPointScale                    = (nil)                                                                 Z_mt.SR_LowFpsMitigations             = (nil)
Z_mt.SR_DynamicMultiPoint                  = (nil)                                                                 Z_mt.SR_LogMissesDueToSpread          = (nil)
Z_mt.SR_SafePoint                          = (nil)                                                                 Z_mt.SR_AntiAimCorrection             = (nil)
Z_mt.SR_PreferBodyAim                      = (nil)                                                                 Z_mt.SR_MaximumFov                    = (nil)
Z_mt.SR_AutomaticFire                      = (nil)                                                                 Z_mt.SR_PreferBodyAimDisablers        = (nil)
Z_mt.SR_AutomaticPenetration               = (nil)                                                                 Z_mt.SR_DelayShotOnUnduck             = (nil)
Z_mt.SR_SilentAim                          = (nil)                                                                 Z_mt.SR_DelayShotOnPeek               = (nil)
Z_mt.SR_MinHitchance                       = (nil)                                                                 Z_mt.SR_DoubleTap                     = (nil)
Z_mt.SR_MinDamage                          = (nil)                                                                 Z_mt.SR_DoubleTapMode                 = (nil)
Z_mt.SR_OverrideAwp                        = (nil)                                                                 Z_mt.SR_MpMode                        = (nil)
Z_mt.SR_AutomaticScope                     = (nil)                                                                 

--------------------------------------------------------------------------------------------------------------ANTI AIM--------------------------------------------------------------------------------------------------
Z_mt.A_Pitch                               = ui.reference("AA", "Anti-aimbot angles", "Pitch")                     Z_mt.A_Enabled                        = ui.reference("AA", "Fake lag", "Enabled")
Z_mt.A_YawBase                             = ui.reference("AA", "Anti-aimbot angles", "Yaw base")                  Z_mt.A_CustomizeTriggers              = ui.reference("AA", "Fake lag", "Customize triggers")
Z_mt.A_Yaw, YawSlider                      = ui.reference("AA", "Anti-aimbot angles", "Yaw")                       Z_mt.A_Triggers                       = ui.reference("AA", "Fake lag", "Triggers")
Z_mt.A_YawJitter, YawJSlider               = ui.reference("AA", "Anti-aimbot angles", "Yaw jitter")                Z_mt.A_Amount                         = ui.reference("AA", "Fake lag", "Amount")
Z_mt.A_BodyYaw, BodyYSlider                = ui.reference("AA", "Anti-aimbot angles", "Body yaw")                  Z_mt.A_Variance                       = ui.reference("AA", "Fake lag", "Variance")
Z_mt.A_FreeStandingBodyYaw                 = ui.reference("AA", "Anti-aimbot angles", "Freestanding body yaw")     Z_mt.A_Limit                          = ui.reference("AA", "Fake lag", "Limit")
Z_mt.A_LowerBodyYawTarget                  = ui.reference("AA", "Anti-aimbot angles", "Lower body yaw target")     Z_mt.A_FakeLagWhileShooting           = ui.reference("AA", "Fake lag", "Fake lag while shooting")
Z_mt.A_FakeYawLimit                        = ui.reference("AA", "Anti-aimbot angles", "Fake yaw limit")            Z_mt.A_ResetOnBunnyHop                = ui.reference("AA", "Fake lag", "Reset on bunny hop")
Z_mt.A_EdgeYaw                             = ui.reference("AA", "Anti-aimbot angles", "Edge yaw")                  Z_mt.A_SlowMotion                     = ui.reference("AA", "Other", "Slow motion")
Z_mt.A_Enabled2                            = ui.reference("AA", "Anti-aimbot angles", "Enabled")                   Z_mt.A_OnShotAntiAim                  = ui.reference("AA", "Other", "On shot anti-aim")
Z_mt.A_FreeStanding                        = ui.reference("AA", "Anti-aimbot angles", "Freestanding")              Z_mt.A_LegMovement                    = ui.reference("AA", "Other", "Leg movement")
Z_mt.A_FreeStandingIgnoreDuck              = ui.reference("AA", "Anti-aimbot angles", "Freestanding ignore duck")  Z_mt.A_SlowMotionType                 = ui.reference("AA", "Other", "Slow motion type")

--------------------------------------------------------------------------------------------------------------STORED ANTI AIM-------------------------------------------------------------------------------------------
Z_mt.SA_Pitch                              = (nil)                                                                 Z_mt.SA_Enabled                       = (nil)
Z_mt.SA_YawBase                            = (nil)                                                                 Z_mt.SA_CustomizeTriggers             = (nil)
Z_mt.SA_Yaw                                = (nil)                                                                 Z_mt.SA_Triggers                      = (nil)
Z_mt.SA_YawJitter                          = (nil)                                                                 Z_mt.SA_Amount                        = (nil)
Z_mt.SA_BodyYaw                            = (nil)                                                                 Z_mt.SA_Variance                      = (nil)
Z_mt.SA_FreeStandingBodyYaw                = (nil)                                                                 Z_mt.SA_Limit                         = (nil)
Z_mt.SA_LowerBodyYawTarget                 = (nil)                                                                 Z_mt.SA_FakeLagWhileShooting          = (nil)
Z_mt.SA_FakeYawLimit                       = (nil)                                                                 Z_mt.SA_ResetOnBunnyHop               = (nil)
Z_mt.SA_EdgeYaw                            = (nil)                                                                 Z_mt.SA_SlowMotion                    = (nil)
Z_mt.SA_SlowMotionType                     = (nil)                                                                 Z_mt.SA_YawSlider                     = (nil)
Z_mt.SA_FreeStanding                       = (nil)                                                                 Z_mt.SA_LegMovement                   = (nil)
Z_mt.SA_FreeStandingIgnoreDuck             = (nil)                                                                 Z_mt.SA_BodyYSlider                   = (nil)
Z_mt.SA_OnShotAntiAim                      = (nil)                                                                 Z_mt.SA_Enabled2                      = (nil)
Z_mt.SA_YawJSlider                         = (nil)

--------------------------------------------------------------------------------------------------------------LEGIT-----------------------------------------------------------------------------------------------------
Z_mt.L_Enabled1                            = ui.reference("LEGIT", "Aimbot", "Enabled")                            Z_mt.L_Enabled2                       = ui.reference("LEGIT", "Triggerbot", "Enabled")
Z_mt.L_Speed                               = ui.reference("LEGIT", "Aimbot", "Speed")                              Z_mt.L_MinHitchance                   = ui.reference("LEGIT", "Triggerbot", "Minimum hit chance")
Z_mt.L_SpeedInAttack                       = ui.reference("LEGIT", "Aimbot", "Speed (in attack)")                  Z_mt.L_ReactionTime2                  = ui.reference("LEGIT", "Triggerbot", "Reaction time")
Z_mt.L_SpeedScaleFov                       = ui.reference("LEGIT", "Aimbot", "Speed scale - FOV")                  Z_mt.L_BurstFire, BurstSlide          = ui.reference("LEGIT", "Triggerbot", "Burst fire")
Z_mt.L_MaximumLockOnTime                   = ui.reference("LEGIT", "Aimbot", "Maximum lock-on time")               Z_mt.L_MinDamage                      = ui.reference("LEGIT", "Triggerbot", "Minimum damage")
Z_mt.L_ReactionTime1                       = ui.reference("LEGIT", "Aimbot", "Reaction time")                      Z_mt.L_AutomaticPenetration           = ui.reference("LEGIT", "Triggerbot", "Automatic penetration")
Z_mt.L_MaximumFov                          = ui.reference("LEGIT", "Aimbot", "Maximum FOV")                        Z_mt.L_Head2                          = ui.reference("LEGIT", "Triggerbot", "Head")
Z_mt.L_Pitch, Yaw                          = ui.reference("LEGIT", "Aimbot", "Recoil compensation (P/Y)")          Z_mt.L_Chest2                         = ui.reference("LEGIT", "Triggerbot", "Chest")
Z_mt.L_QickStop                            = ui.reference("LEGIT", "Aimbot", "Quick stop")                         Z_mt.L_Stomach2                       = ui.reference("LEGIT", "Triggerbot", "Stomach")
Z_mt.L_AimThroughSmoke                     = ui.reference("LEGIT", "Aimbot", "Aim through smoke")                  Z_mt.L_AccuracyBoost                  = ui.reference("LEGIT", "Other", "Accuracy boost")
Z_mt.L_AimWhileBlind                       = ui.reference("LEGIT", "Aimbot", "Aim while blind")                    Z_mt.L_AccuracyBoostRange             = ui.reference("LEGIT", "Other", "Accuracy boost range")
Z_mt.L_Head1                               = ui.reference("LEGIT", "Aimbot", "Head")                               Z_mt.L_StandAloneRecoilCompensation   = ui.reference("LEGIT", "Other", "Standalone recoil compensation")
Z_mt.L_Chest1                              = ui.reference("LEGIT", "Aimbot", "Chest")
Z_mt.L_Stomach1                            = ui.reference("LEGIT", "Aimbot", "Stomach")

--------------------------------------------------------------------------------------------------------------STORED LEGIT----------------------------------------------------------------------------------------------
-- Pistol
Z_mt.SLA_Enabled1                          = (nil)                                                                 Z_mt.SLA_Enabled2                     = (nil)
Z_mt.SLA_Speed                             = (nil)                                                                 Z_mt.SLA_MinHitchance                 = (nil)
Z_mt.SLA_SpeedInAttack                     = (nil)                                                                 Z_mt.SLA_ReactionTime2                = (nil)
Z_mt.SLA_SpeedScaleFov                     = (nil)                                                                 Z_mt.SLA_BurstFire                    = (nil)
Z_mt.SLA_MaximumLockOnTime                 = (nil)                                                                 Z_mt.SLA_BurstSlide                   = (nil)
Z_mt.SLA_ReactionTime1                     = (nil)                                                                 Z_mt.SLA_MinDamage                    = (nil)
Z_mt.SLA_MaximumFov                        = (nil)                                                                 Z_mt.SLA_AutomaticPenetration         = (nil)
Z_mt.SLA_Pitch                             = (nil)                                                                 Z_mt.SLA_Head2                        = (nil)
Z_mt.SLA_Yaw                               = (nil)                                                                 Z_mt.SLA_Chest2                       = (nil)
Z_mt.SLA_QickStop                          = (nil)                                                                 Z_mt.SLA_Stomach2                     = (nil)
Z_mt.SLA_AimThroughSmoke                   = (nil)                                                                 Z_mt.SLA_AccuracyBoost                = (nil)
Z_mt.SLA_AimWhileBlind                     = (nil)                                                                 Z_mt.SLA_AccuracyBoostRange           = (nil)
Z_mt.SLA_Head1                             = (nil)                                                                 Z_mt.SLA_StandAloneRecoilCompensation = (nil)
Z_mt.SLA_Chest1                            = (nil)
Z_mt.SLA_Stomach1                          = (nil)
-- Smg
Z_mt.SLB_Enabled1                          = (nil)                                                                 Z_mt.SLB_Enabled2                     = (nil)
Z_mt.SLB_Speed                             = (nil)                                                                 Z_mt.SLB_MinHitchance                 = (nil)
Z_mt.SLB_SpeedInAttack                     = (nil)                                                                 Z_mt.SLB_ReactionTime2                = (nil)
Z_mt.SLB_SpeedScaleFov                     = (nil)                                                                 Z_mt.SLB_BurstFire                    = (nil)
Z_mt.SLB_MaximumLockOnTime                 = (nil)                                                                 Z_mt.SLB_BurstSlide                   = (nil)
Z_mt.SLB_ReactionTime1                     = (nil)                                                                 Z_mt.SLB_MinDamage                    = (nil)
Z_mt.SLB_MaximumFov                        = (nil)                                                                 Z_mt.SLB_AutomaticPenetration         = (nil)
Z_mt.SLB_Pitch                             = (nil)                                                                 Z_mt.SLB_Head2                        = (nil)
Z_mt.SLB_Yaw                               = (nil)                                                                 Z_mt.SLB_Chest2                       = (nil)
Z_mt.SLB_QickStop                          = (nil)                                                                 Z_mt.SLB_Stomach2                     = (nil)
Z_mt.SLB_AimThroughSmoke                   = (nil)                                                                 Z_mt.SLB_AccuracyBoost                = (nil)
Z_mt.SLB_AimWhileBlind                     = (nil)                                                                 Z_mt.SLB_AccuracyBoostRanget          = (nil)
Z_mt.SLB_Head1                             = (nil)                                                                 Z_mt.SLB_StandAloneRecoilCompensation = (nil)
Z_mt.SLB_Chest1                            = (nil)
Z_mt.SLB_Stomach1                          = (nil)
-- Rifle
Z_mt.SLC_Enabled1                          = (nil)                                                                 Z_mt.SLC_Enabled2                     = (nil)
Z_mt.SLC_Speed                             = (nil)                                                                 Z_mt.SLC_MinHitchance                 = (nil)
Z_mt.SLC_SpeedInAttack                     = (nil)                                                                 Z_mt.SLC_ReactionTime2                = (nil)
Z_mt.SLC_SpeedScaleFov                     = (nil)                                                                 Z_mt.SLC_BurstFire                    = (nil)
Z_mt.SLC_MaximumLockOnTime                 = (nil)                                                                 Z_mt.SLC_BurstSlide                   = (nil)
Z_mt.SLC_ReactionTime1                     = (nil)                                                                 Z_mt.SLC_MinDamage                    = (nil)
Z_mt.SLC_MaximumFov                        = (nil)                                                                 Z_mt.SLC_AutomaticPenetration         = (nil)
Z_mt.SLC_Pitch                             = (nil)                                                                 Z_mt.SLC_Head2                        = (nil)
Z_mt.SLC_Yaw                               = (nil)                                                                 Z_mt.SLC_Chest2                       = (nil)
Z_mt.SLC_QickStop                          = (nil)                                                                 Z_mt.SLC_Stomach2                     = (nil)
Z_mt.SLC_AimThroughSmoke                   = (nil)                                                                 Z_mt.SLC_AccuracyBoost                = (nil)
Z_mt.SLC_AimWhileBlind                     = (nil)                                                                 Z_mt.SLC_AccuracyBoostRanget          = (nil)
Z_mt.SLC_Head1                             = (nil)                                                                 Z_mt.SLC_StandAloneRecoilCompensation = (nil)
Z_mt.SLC_Chest1                            = (nil)
Z_mt.SLC_Stomach1                          = (nil)
-- Shotgun
Z_mt.SLD_Enabled1                          = (nil)                                                                 Z_mt.SLD_Enabled2                     = (nil)
Z_mt.SLD_Speed                             = (nil)                                                                 Z_mt.SLD_MinHitchance                 = (nil)
Z_mt.SLD_SpeedInAttack                     = (nil)                                                                 Z_mt.SLD_ReactionTime2                = (nil)
Z_mt.SLD_SpeedScaleFov                     = (nil)                                                                 Z_mt.SLD_BurstFire                    = (nil)
Z_mt.SLD_MaximumLockOnTime                 = (nil)                                                                 Z_mt.SLD_BurstSlide                   = (nil)
Z_mt.SLD_ReactionTime1                     = (nil)                                                                 Z_mt.SLD_MinDamage                    = (nil)
Z_mt.SLD_MaximumFov                        = (nil)                                                                 Z_mt.SLD_AutomaticPenetration         = (nil)
Z_mt.SLD_Pitch                             = (nil)                                                                 Z_mt.SLD_Head2                        = (nil)
Z_mt.SLD_Yaw                               = (nil)                                                                 Z_mt.SLD_Chest2                       = (nil)
Z_mt.SLD_QickStop                          = (nil)                                                                 Z_mt.SLD_Stomach2                     = (nil)
Z_mt.SLD_AimThroughSmoke                   = (nil)                                                                 Z_mt.SLD_AccuracyBoost                = (nil)
Z_mt.SLD_AimWhileBlind                     = (nil)                                                                 Z_mt.SLD_AccuracyBoostRanget          = (nil)
Z_mt.SLD_Head1                             = (nil)                                                                 Z_mt.SLD_StandAloneRecoilCompensation = (nil)
Z_mt.SLD_Chest1                            = (nil)
Z_mt.SLD_Stomach1                          = (nil)
-- Machinegun
Z_mt.SLE_Enabled1                          = (nil)                                                                 Z_mt.SLE_Enabled2                     = (nil)
Z_mt.SLE_Speed                             = (nil)                                                                 Z_mt.SLE_MinHitchance                 = (nil)
Z_mt.SLE_SpeedInAttack                     = (nil)                                                                 Z_mt.SLE_ReactionTime2                = (nil)
Z_mt.SLE_SpeedScaleFov                     = (nil)                                                                 Z_mt.SLE_BurstFire                    = (nil)
Z_mt.SLE_MaximumLockOnTime                 = (nil)                                                                 Z_mt.SLE_BurstSlide                   = (nil)
Z_mt.SLE_ReactionTime1                     = (nil)                                                                 Z_mt.SLE_MinDamage                    = (nil)
Z_mt.SLE_MaximumFov                        = (nil)                                                                 Z_mt.SLE_AutomaticPenetration         = (nil)
Z_mt.SLE_Pitch                             = (nil)                                                                 Z_mt.SLE_Head2                        = (nil)
Z_mt.SLE_Yaw                               = (nil)                                                                 Z_mt.SLE_Chest2                       = (nil)
Z_mt.SLE_QickStop                          = (nil)                                                                 Z_mt.SLE_Stomach2                     = (nil)
Z_mt.SLE_AimThroughSmoke                   = (nil)                                                                 Z_mt.SLE_AccuracyBoost                = (nil)
Z_mt.SLE_AimWhileBlind                     = (nil)                                                                 Z_mt.SLE_AccuracyBoostRanget          = (nil)
Z_mt.SLE_Head1                             = (nil)                                                                 Z_mt.SLE_StandAloneRecoilCompensation = (nil)
Z_mt.SLE_Chest1                            = (nil)
Z_mt.SLE_Stomach1                          = (nil)
-- Sniper
Z_mt.SLF_Enabled1                          = (nil)                                                                 Z_mt.SLF_Enabled2                     = (nil)
Z_mt.SLF_Speed                             = (nil)                                                                 Z_mt.SLF_MinHitchance                 = (nil)
Z_mt.SLF_SpeedInAttack                     = (nil)                                                                 Z_mt.SLF_ReactionTime2                = (nil)
Z_mt.SLF_SpeedScaleFov                     = (nil)                                                                 Z_mt.SLF_BurstFire                    = (nil)
Z_mt.SLF_MaximumLockOnTime                 = (nil)                                                                 Z_mt.SLF_BurstSlide                   = (nil)
Z_mt.SLF_ReactionTime1                     = (nil)                                                                 Z_mt.SLF_MinDamage                    = (nil)
Z_mt.SLF_MaximumFov                        = (nil)                                                                 Z_mt.SLF_AutomaticPenetration         = (nil)
Z_mt.SLF_Pitch                             = (nil)                                                                 Z_mt.SLF_Head2                        = (nil)
Z_mt.SLF_Yaw                               = (nil)                                                                 Z_mt.SLF_Chest2                       = (nil)
Z_mt.SLF_QickStop                          = (nil)                                                                 Z_mt.SLF_Stomach2                     = (nil)
Z_mt.SLF_AimThroughSmoke                   = (nil)                                                                 Z_mt.SLF_AccuracyBoost                = (nil)
Z_mt.SLF_AimWhileBlind                     = (nil)                                                                 Z_mt.SLF_AccuracyBoostRanget          = (nil)
Z_mt.SLF_Head1                             = (nil)                                                                 Z_mt.SLF_StandAloneRecoilCompensation = (nil)
Z_mt.SLF_Chest1                            = (nil)
Z_mt.SLF_Stomach1                          = (nil)

--------------------------------------------------------------------------------------------------------------VISUALS---------------------------------------------------------------------------------------------------
Z_mt.V_Teammates                           = ui.reference("VISUALS", "Player ESP", "Teammates")                    Z_mt.V_Radar                          = ui.reference("VISUALS", "Other ESP", "Radar")
Z_mt.V_Dormant                             = ui.reference("VISUALS", "Player ESP", "Dormant")                      Z_mt.V_DroppedWeapon, Color23         = ui.reference("VISUALS", "Other ESP", "Dropped weapons")
Z_mt.V_BoundingBox, Color1                 = ui.reference("VISUALS", "Player ESP", "Bounding box")                 Z_mt.V_DroppedWeaponAmmo              = ui.reference("VISUALS", "Other ESP", "Dropped weapon ammo")
Z_mt.V_HealthBar                           = ui.reference("VISUALS", "Player ESP", "Health bar")                   Z_mt.V_Grenades, Color24              = ui.reference("VISUALS", "Other ESP", "Grenades")
Z_mt.V_Name, Color2                        = ui.reference("VISUALS", "Player ESP", "Name")                         Z_mt.V_InaccuracyOverlay, Color25     = ui.reference("VISUALS", "Other ESP", "Inaccuracy overlay")
Z_mt.V_Flags                               = ui.reference("VISUALS", "Player ESP", "Flags")                        Z_mt.V_RecoilOverlay                  = ui.reference("VISUALS", "Other ESP", "Recoil overlay")
Z_mt.V_WeaponText                          = ui.reference("VISUALS", "Player ESP", "Weapon text")                  Z_mt.V_Crosshair                      = ui.reference("VISUALS", "Other ESP", "Crosshair")
Z_mt.V_WeaponIcon, Color3                  = ui.reference("VISUALS", "Player ESP", "Weapon icon")                  Z_mt.V_Bomb, Color26                  = ui.reference("VISUALS", "Other ESP", "Bomb")
Z_mt.V_Ammo, Color4                        = ui.reference("VISUALS", "Player ESP", "Ammo")                         Z_mt.V_GrenadeTrajectory, Color27     = ui.reference("VISUALS", "Other ESP", "Grenade trajectory")
Z_mt.V_Distance                            = ui.reference("VISUALS", "Player ESP", "Distance")                     Z_mt.V_GrenadeProximityWarning        = ui.reference("VISUALS", "Other ESP", "Grenade proximity warning")
Z_mt.V_Glow, Color5                        = ui.reference("VISUALS", "Player ESP", "Glow")                         Z_mt.V_Spectators                     = ui.reference("VISUALS", "Other ESP", "Spectators")
Z_mt.V_HitMarker                           = ui.reference("VISUALS", "Player ESP", "Hit marker")                   Z_mt.V_PenetrationReticle             = ui.reference("VISUALS", "Other ESP", "Penetration reticle")
Z_mt.V_HitMarkerSound                      = ui.reference("VISUALS", "Player ESP", "Hit marker sound")             Z_mt.V_Hostages, Color28              = ui.reference("VISUALS", "Other ESP", "Hostages")
Z_mt.V_VisualizeSounds, Color6             = ui.reference("VISUALS", "Player ESP", "Visualize sounds")             Z_mt.V_SharedEsp                      = ui.reference("VISUALS", "Other ESP", "Shared ESP")
Z_mt.V_LineOfSight, Color7                 = ui.reference("VISUALS", "Player ESP", "Line of sight")                Z_mt.V_SharedEspWithOtherTeam         = ui.reference("VISUALS", "Other ESP", "Shared ESP with other team")
Z_mt.V_Money                               = ui.reference("VISUALS", "Player ESP", "Money")                        Z_mt.V_RestrictSharedEspUpdates       = ui.reference("VISUALS", "Other ESP", "Restrict shared ESP updates")
Z_mt.V_Skeleton, Color8                    = ui.reference("VISUALS", "Player ESP", "Skeleton")                     Z_mt.V_UpgradeTablet                  = ui.reference("VISUALS", "Other ESP", "Upgrade tablet")
Z_mt.V_OOFA, Color9, Pos, Size             = ui.reference("VISUALS", "Player ESP", "Out of FOV arrow")             Z_mt.V_DangerZoneItems                = ui.reference("VISUALS", "Other ESP", "Danger Zone items")
Z_mt.V_Player, Color10                     = ui.reference("VISUALS", "Colored models", "Player")                   Z_mt.V_DroneGun, Color29              = ui.reference("VISUALS", "Other ESP", "Drone gun")
Z_mt.V_Pbw, Color11, Cham1, Color12        = ui.reference("VISUALS", "Colored models", "Player behind wall")       Z_mt.V_BlackHawk, Color30             = ui.reference("VISUALS", "Other ESP", "Blackhawk")
Z_mt.V_Teammate, Color13                   = ui.reference("VISUALS", "Colored models", "Teammate")                 Z_mt.V_Drone, Color31                 = ui.reference("VISUALS", "Other ESP", "Drone")
Z_mt.V_Tbw, Color14, Cham2, Color15        = ui.reference("VISUALS", "Colored models", "Teammate behind wall")     Z_mt.V_RandomCase, Color32            = ui.reference("VISUALS", "Other ESP", "Random case")
Z_mt.V_LPlayer, Color16, Cham3, Color17    = ui.reference("VISUALS", "Colored models", "Local player")             Z_mt.V_ToolCase, Color33              = ui.reference("VISUALS", "Other ESP", "Tool case")
Z_mt.V_LPlayerF, Color18, Cham4, Color19   = ui.reference("VISUALS", "Colored models", "Local player fake")        Z_mt.V_PistolCase, Color34            = ui.reference("VISUALS", "Other ESP", "Pistol case")
Z_mt.V_Hands, Color20, Cham5, Color21      = ui.reference("VISUALS", "Colored models", "Hands")                    Z_mt.V_ExplosiveCase, Color35         = ui.reference("VISUALS", "Other ESP", "Explosive case")
Z_mt.V_DisableModelOcclusion               = ui.reference("VISUALS", "Colored models", "Disable model occlusion")  Z_mt.V_HeavyWeaponCase, Color36       = ui.reference("VISUALS", "Other ESP", "Heavy weapon case")
Z_mt.V_Shadow, Color22                     = ui.reference("VISUALS", "Colored models", "Shadow")                   Z_mt.V_LightWeaponCase, Color37       = ui.reference("VISUALS", "Other ESP", "Light weapon case")
Z_mt.V_Props, Color48                      = ui.reference("VISUALS", "Colored models", "Props")                    Z_mt.V_DuffleBag, Color38             = ui.reference("VISUALS", "Other ESP", "Dufflebag")
Z_mt.V_RemoveSmoke                         = ui.reference("VISUALS", "Effects", "Remove smoke grenades")           Z_mt.V_Jammer, Color39                = ui.reference("VISUALS", "Other ESP", "Jammer")
Z_mt.V_RemoveFog                           = ui.reference("VISUALS", "Effects", "Remove fog")                      Z_mt.V_Ammobox, Color40               = ui.reference("VISUALS", "Other ESP", "Ammobox")
Z_mt.V_RemoveSkybox                        = ui.reference("VISUALS", "Effects", "Remove skybox")                   Z_mt.V_Armor, Color41                 = ui.reference("VISUALS", "Other ESP", "Armor")
Z_mt.V_VisualRecoilAdjustment              = ui.reference("VISUALS", "Effects", "Visual recoil adjustment")        Z_mt.V_ParachutePack, Color42         = ui.reference("VISUALS", "Other ESP", "Parachute pack")
Z_mt.V_TransparentWalls                    = ui.reference("VISUALS", "Effects", "Transparent walls")               Z_mt.V_Briefcase, Color43             = ui.reference("VISUALS", "Other ESP", "Briefcase")
Z_mt.V_TransparentProps                    = ui.reference("VISUALS", "Effects", "Transparent props")               Z_mt.V_TabletUpgradeZone, Color44     = ui.reference("VISUALS", "Other ESP", "Tablet upgrade drone")
Z_mt.V_BrightnessAdjustment, Color49       = ui.reference("VISUALS", "Effects", "Brightness adjustment")           Z_mt.V_TabletUpgradeDrone, Color45    = ui.reference("VISUALS", "Other ESP", "Tablet upgrade zone")
Z_mt.V_RemoveScope                         = ui.reference("VISUALS", "Effects", "Remove scope overlay")            Z_mt.V_CashStack, Color46             = ui.reference("VISUALS", "Other ESP", "Cash stack")
Z_mt.V_DisableTeammates                    = ui.reference("VISUALS", "Effects", "Disable rendering of teammates")  Z_mt.V_BulletImpacts, Duration        = ui.reference("VISUALS", "Effects", "Bullet impacts")
Z_mt.V_DisablePostProcessing               = ui.reference("VISUALS", "Effects", "Disable post processing")         Z_mt.V_BulletTracers, Color47         = ui.reference("VISUALS", "Effects", "Bullet tracers")
Z_mt.V_ForceThirdPersonAlive               = ui.reference("VISUALS", "Effects", "Force third person (alive)")      Z_mt.V_InstantScope                   = ui.reference("VISUALS", "Effects", "Instant scope")  
Z_mt.V_ForceThirdPersonDead                = ui.reference("VISUALS", "Effects", "Force third person (dead)")       Z_mt.V_RemoveFlash                    = ui.reference("VISUALS", "Effects", "Remove flashbang effects")

--------------------------------------------------------------------------------------------------------------STORED VISUALS--------------------------------------------------------------------------------------------
Z_mt.SV_Teammates                          = (nil)                                                                 Z_mt.SV_Radar                         = (nil)
Z_mt.SV_Dormant                            = (nil)                                                                 Z_mt.SV_DroppedWeapon                 = (nil)
Z_mt.SV_BoundingBox                        = (nil)                                                                 Z_mt.SV_DroppedWeaponAmmo             = (nil)
Z_mt.SV_HealthBar                          = (nil)                                                                 Z_mt.SV_Grenades                      = (nil)
Z_mt.SV_Name                               = (nil)                                                                 Z_mt.SV_InaccuracyOverlay             = (nil)
Z_mt.SV_Flags                              = (nil)                                                                 Z_mt.SV_RecoilOverlay                 = (nil)
Z_mt.SV_WeaponText                         = (nil)                                                                 Z_mt.SV_Crosshair                     = (nil)
Z_mt.SV_WeaponIcon                         = (nil)                                                                 Z_mt.SV_Bomb                          = (nil)
Z_mt.SV_Ammo                               = (nil)                                                                 Z_mt.SV_GrenadeTrajectory             = (nil)
Z_mt.SV_Distance                           = (nil)                                                                 Z_mt.SV_GrenadeProximityWarning       = (nil)
Z_mt.SV_Glow                               = (nil)                                                                 Z_mt.SV_Spectators                    = (nil)
Z_mt.SV_HitMarker                          = (nil)                                                                 Z_mt.SV_PenetrationReticle            = (nil)
Z_mt.SV_HitMarkerSound                     = (nil)                                                                 Z_mt.SV_Hostages                      = (nil)
Z_mt.SV_VisualizeSounds                    = (nil)                                                                 Z_mt.SV_SharedEsp                     = (nil)
Z_mt.SV_LineOfSight                        = (nil)                                                                 Z_mt.SV_SharedEspWithOtherTeam        = (nil)
Z_mt.SV_Money                              = (nil)                                                                 Z_mt.SV_RestrictSharedEspUpdates      = (nil)
Z_mt.SV_Skeleton                           = (nil)                                                                 Z_mt.SV_UpgradeTablet                 = (nil)
Z_mt.SV_OOFA                               = (nil)                                                                 Z_mt.SV_DangerZoneItems               = (nil)
Z_mt.SV_Player                             = (nil)                                                                 Z_mt.SV_DroneGun                      = (nil)
Z_mt.SV_Pbw                                = (nil)                                                                 Z_mt.SV_BlackHawk                     = (nil)
Z_mt.SV_Teammate                           = (nil)                                                                 Z_mt.SV_Drone                         = (nil)
Z_mt.SV_Tbw                                = (nil)                                                                 Z_mt.SV_RandomCase                    = (nil)
Z_mt.SV_LPlayer                            = (nil)                                                                 Z_mt.SV_ToolCase                      = (nil)
Z_mt.SV_LPlayerF                           = (nil)                                                                 Z_mt.SV_PistolCase                    = (nil)
Z_mt.SV_Hands                              = (nil)                                                                 Z_mt.SV_ExplosiveCase                 = (nil)
Z_mt.SV_DisableModelOcclusion              = (nil)                                                                 Z_mt.SV_HeavyWeaponCase               = (nil)
Z_mt.SV_Shadow                             = (nil)                                                                 Z_mt.SV_LightWeaponCase               = (nil)
Z_mt.SV_RemoveFlash                        = (nil)                                                                 Z_mt.SV_DuffleBag                     = (nil)
Z_mt.SV_RemoveSmoke                        = (nil)                                                                 Z_mt.SV_Jammer                        = (nil)
Z_mt.SV_RemoveFog                          = (nil)                                                                 Z_mt.SV_Ammobox                       = (nil)
Z_mt.SV_RemoveSkybox                       = (nil)                                                                 Z_mt.SV_Armor                         = (nil)
Z_mt.SV_VisualRecoilAdjustment             = (nil)                                                                 Z_mt.SV_ParachutePack                 = (nil)
Z_mt.SV_TransparentWalls                   = (nil)                                                                 Z_mt.SV_Briefcase                     = (nil)
Z_mt.SV_TransparentProps                   = (nil)                                                                 Z_mt.SV_TabletUpgradeZone             = (nil)
Z_mt.SV_BrightnessAdjustment               = (nil)                                                                 Z_mt.SV_TabletUpgradeDrone            = (nil)
Z_mt.SV_RemoveScope                        = (nil)                                                                 Z_mt.SV_CashStack                     = (nil)
Z_mt.SV_InstantScope                       = (nil)                                                                 Z_mt.SV_Pos                           = (nil)
Z_mt.SV_DisablePostProcessing              = (nil)                                                                 Z_mt.SV_Size                          = (nil)
Z_mt.SV_ForceThirdPersonAlive              = (nil)                                                                 Z_mt.SV_Cham1                         = (nil)
Z_mt.SV_ForceThirdPersonDead               = (nil)                                                                 Z_mt.SV_Cham2                         = (nil)
Z_mt.SV_DisableTeammates                   = (nil)                                                                 Z_mt.SV_Cham3                         = (nil)
Z_mt.SV_BulletTracers                      = (nil)                                                                 Z_mt.SV_Cham4                         = (nil)
Z_mt.SV_BulletImpacts                      = (nil)                                                                 Z_mt.SV_Cham5                         = (nil)
Z_mt.SV_Duration                           = (nil)                                                                 Z_mt.SV_Props                         = (nil)

-- Colors (R,B,G,A)
Z_mt.R1  = (nil)     Z_mt.R26 = (nil)               Z_mt.B1  = (nil)     Z_mt.B26 = (nil)               Z_mt.G1  = (nil)     Z_mt.G26 = (nil)               Z_mt.G1  = (nil)     Z_mt.G26 = (nil)
Z_mt.R2  = (nil)     Z_mt.R27 = (nil)               Z_mt.B2  = (nil)     Z_mt.B27 = (nil)               Z_mt.G2  = (nil)     Z_mt.G27 = (nil)               Z_mt.G2  = (nil)     Z_mt.G27 = (nil)
Z_mt.R3  = (nil)     Z_mt.R28 = (nil)               Z_mt.B3  = (nil)     Z_mt.B28 = (nil)               Z_mt.G3  = (nil)     Z_mt.G28 = (nil)               Z_mt.G3  = (nil)     Z_mt.G28 = (nil)
Z_mt.R4  = (nil)     Z_mt.R29 = (nil)               Z_mt.B4  = (nil)     Z_mt.B29 = (nil)               Z_mt.G4  = (nil)     Z_mt.G29 = (nil)               Z_mt.G4  = (nil)     Z_mt.G29 = (nil)
Z_mt.R5  = (nil)     Z_mt.R30 = (nil)               Z_mt.B5  = (nil)     Z_mt.B30 = (nil)               Z_mt.G5  = (nil)     Z_mt.G30 = (nil)               Z_mt.G5  = (nil)     Z_mt.G30 = (nil)
Z_mt.R6  = (nil)     Z_mt.R31 = (nil)               Z_mt.B6  = (nil)     Z_mt.B31 = (nil)               Z_mt.G6  = (nil)     Z_mt.G31 = (nil)               Z_mt.G6  = (nil)     Z_mt.G31 = (nil)
Z_mt.R7  = (nil)     Z_mt.R32 = (nil)               Z_mt.B7  = (nil)     Z_mt.B32 = (nil)               Z_mt.G7  = (nil)     Z_mt.G32 = (nil)               Z_mt.G7  = (nil)     Z_mt.G32 = (nil)
Z_mt.R8  = (nil)     Z_mt.R33 = (nil)               Z_mt.B8  = (nil)     Z_mt.B33 = (nil)               Z_mt.G8  = (nil)     Z_mt.G33 = (nil)               Z_mt.G8  = (nil)     Z_mt.G33 = (nil)
Z_mt.R9  = (nil)     Z_mt.R34 = (nil)               Z_mt.B9  = (nil)     Z_mt.B34 = (nil)               Z_mt.G9  = (nil)     Z_mt.G34 = (nil)               Z_mt.G9  = (nil)     Z_mt.G34 = (nil)
Z_mt.R10 = (nil)     Z_mt.R35 = (nil)               Z_mt.B10 = (nil)     Z_mt.B35 = (nil)               Z_mt.G10 = (nil)     Z_mt.G35 = (nil)               Z_mt.G10 = (nil)     Z_mt.G35 = (nil)
Z_mt.R11 = (nil)     Z_mt.R36 = (nil)               Z_mt.B11 = (nil)     Z_mt.B36 = (nil)               Z_mt.G11 = (nil)     Z_mt.G36 = (nil)               Z_mt.G11 = (nil)     Z_mt.G36 = (nil)
Z_mt.R12 = (nil)     Z_mt.R37 = (nil)               Z_mt.B12 = (nil)     Z_mt.B37 = (nil)               Z_mt.G12 = (nil)     Z_mt.G37 = (nil)               Z_mt.G12 = (nil)     Z_mt.G37 = (nil)
Z_mt.R13 = (nil)     Z_mt.R38 = (nil)               Z_mt.B13 = (nil)     Z_mt.B38 = (nil)               Z_mt.G13 = (nil)     Z_mt.G38 = (nil)               Z_mt.G13 = (nil)     Z_mt.G38 = (nil)
Z_mt.R14 = (nil)     Z_mt.R39 = (nil)               Z_mt.B14 = (nil)     Z_mt.B39 = (nil)               Z_mt.G14 = (nil)     Z_mt.G39 = (nil)               Z_mt.G14 = (nil)     Z_mt.G39 = (nil)
Z_mt.R15 = (nil)     Z_mt.R40 = (nil)               Z_mt.B15 = (nil)     Z_mt.B40 = (nil)               Z_mt.G15 = (nil)     Z_mt.G40 = (nil)               Z_mt.G15 = (nil)     Z_mt.G40 = (nil)
Z_mt.R16 = (nil)     Z_mt.R41 = (nil)               Z_mt.B16 = (nil)     Z_mt.B41 = (nil)               Z_mt.G16 = (nil)     Z_mt.G41 = (nil)               Z_mt.G16 = (nil)     Z_mt.G41 = (nil)
Z_mt.R17 = (nil)     Z_mt.R42 = (nil)               Z_mt.B17 = (nil)     Z_mt.B42 = (nil)               Z_mt.G17 = (nil)     Z_mt.G42 = (nil)               Z_mt.G17 = (nil)     Z_mt.G42 = (nil)
Z_mt.R18 = (nil)     Z_mt.R43 = (nil)               Z_mt.B18 = (nil)     Z_mt.B43 = (nil)               Z_mt.G18 = (nil)     Z_mt.G43 = (nil)               Z_mt.G18 = (nil)     Z_mt.G43 = (nil)
Z_mt.R19 = (nil)     Z_mt.R44 = (nil)               Z_mt.B19 = (nil)     Z_mt.B44 = (nil)               Z_mt.G19 = (nil)     Z_mt.G44 = (nil)               Z_mt.G19 = (nil)     Z_mt.G44 = (nil)
Z_mt.R21 = (nil)     Z_mt.R46 = (nil)               Z_mt.B21 = (nil)     Z_mt.B46 = (nil)               Z_mt.G21 = (nil)     Z_mt.G46 = (nil)               Z_mt.G21 = (nil)     Z_mt.G46 = (nil)
Z_mt.R20 = (nil)     Z_mt.R45 = (nil)               Z_mt.B20 = (nil)     Z_mt.B45 = (nil)               Z_mt.G20 = (nil)     Z_mt.G45 = (nil)               Z_mt.G20 = (nil)     Z_mt.G45 = (nil)
Z_mt.R22 = (nil)     Z_mt.R47 = (nil)               Z_mt.B22 = (nil)     Z_mt.B47 = (nil)               Z_mt.G22 = (nil)     Z_mt.G47 = (nil)               Z_mt.G22 = (nil)     Z_mt.G47 = (nil)
Z_mt.R23 = (nil)     Z_mt.R48 = (nil)               Z_mt.B23 = (nil)     Z_mt.B48 = (nil)               Z_mt.G23 = (nil)     Z_mt.G48 = (nil)               Z_mt.G23 = (nil)     Z_mt.G48 = (nil)
Z_mt.R24 = (nil)     Z_mt.R49 = (nil)               Z_mt.B24 = (nil)     Z_mt.B49 = (nil)               Z_mt.G24 = (nil)     Z_mt.G49 = (nil)               Z_mt.G24 = (nil)     Z_mt.G49 = (nil)
Z_mt.R25 = (nil)                                    Z_mt.B25 = (nil)                                    Z_mt.G25 = (nil)                                    Z_mt.G25 = (nil)
--------------------------------------------------------------------------------------------------------------MISC------------------------------------------------------------------------------------------------------
Z_mt.M_StandaloneQuickStop                 = ui.reference("MISC", "Movement", "Standalone quick stop")             Z_mt.M_RevealCompetitiveRanks         = ui.reference("MISC", "Miscellaneous", "Reveal competitive ranks")
Z_mt.M_BunnyHop                            = ui.reference("MISC", "Movement", "Bunny hop")                         Z_mt.M_AutoAcceptMatchmaking          = ui.reference("MISC", "Miscellaneous", "Auto-accept matchmaking")
Z_mt.M_AirStrafe                           = ui.reference("MISC", "Movement", "Air strafe")                        Z_mt.M_AutomaticGrenadeRelease        = ui.reference("MISC", "Miscellaneous", "Automatic grenade release")
Z_mt.M_AirStrafeDirection                  = ui.reference("MISC", "Movement", "Air strafe direction")              Z_mt.M_PingSpike, zz, PingVal         = ui.reference("MISC", "Miscellaneous", "Ping spike")
Z_mt.M_AirStrafeSmoothing                  = ui.reference("MISC", "Movement", "Air strafe smoothing")              Z_mt.M_OverrideFov                    = ui.reference("MISC", "Miscellaneous", "Override FOV")
Z_mt.M_Zhop, zz, Zy, Zx                    = ui.reference("MISC", "Movement", "Z-Hop")                             Z_mt.M_PersistentKillFeed             = ui.reference("MISC", "Miscellaneous", "Persistent kill feed")
Z_mt.M_PreSpeed                            = ui.reference("MISC", "Movement", "Pre-speed")                         Z_mt.M_ZeusBot                        = ui.reference("MISC", "Miscellaneous", "Zeusbot")
Z_mt.M_AirDuck                             = ui.reference("MISC", "Movement", "Air duck")                          Z_mt.M_LogPurchases                   = ui.reference("MISC", "Miscellaneous", "Log weapon purchases")
Z_mt.M_InfiniteDuck                        = ui.reference("MISC", "Movement", "Infinite duck")                     Z_mt.M_RevealOverwatchPlayers         = ui.reference("MISC", "Miscellaneous", "Reveal Overwatch players")
Z_mt.M_FastWalk                            = ui.reference("MISC", "Movement", "Fast walk")                         Z_mt.M_KnifeBot, KnifeMode            = ui.reference("MISC", "Miscellaneous", "Knifebot")
Z_mt.M_BlockBot                            = ui.reference("MISC", "Movement", "Blockbot")                          Z_mt.M_AutomaticWeapons, ADelay       = ui.reference("MISC", "Miscellaneous", "Automatic weapons")
Z_mt.M_EasyStrafe                          = ui.reference("MISC", "Movement", "Easy strafe")                       Z_mt.M_AntiUntrusted                  = ui.reference("MISC", "Settings", "Anti-untrusted")
Z_mt.M_JumpAtEdge                          = ui.reference("MISC", "Movement", "Jump at edge")                      Z_mt.M_HideFromObs                    = ui.reference("MISC", "Settings", "Hide from OBS")
Z_mt.M_ClanTagSpammer                      = ui.reference("MISC", "Miscellaneous", "Clan tag spammer")             Z_mt.M_LockMenuLayout                 = ui.reference("MISC", "Settings", "Lock menu layout")
Z_mt.M_LogDamageDealt                      = ui.reference("MISC", "Miscellaneous", "Log damage dealt")             Z_mt.M_LowFpsWarning                  = ui.reference("MISC", "Settings", "Low FPS warning")
Z_mt.M_OverrideZoomFov                     = ui.reference("MISC", "Miscellaneous", "Override Zoom FOV")

--------------------------------------------------------------------------------------------------------------STORED MISC-----------------------------------------------------------------------------------------------
Z_mt.SM_OverrideFov                  = (nil)                                                                 Z_mt.SM_AutomaticWeapons        = (nil)
Z_mt.SM_BunnyHop                     = (nil)                                                                 Z_mt.SM_JumpAtEdge              = (nil)
Z_mt.SM_AirStrafe                    = (nil)                                                                 Z_mt.SM_RevealCompetitveRanks   = (nil)
Z_mt.SM_AirStrafeDirection           = (nil)                                                                 Z_mt.SM_AutoAcceptMatchmaking   = (nil)
Z_mt.SM_AirStrafeSmoothing           = (nil)                                                                 Z_mt.SM_AutomaticGrenadeRelease = (nil)
Z_mt.SM_Zhop                         = (nil)                                                                 Z_mt.SM_PingSpike               = (nil)
Z_mt.SM_PreSpeed                     = (nil)                                                                 Z_mt.SM_FastWalk                = (nil)
Z_mt.SM_AirDuck                      = (nil)                                                                 Z_mt.SM_PersistentKillFeed      = (nil)
Z_mt.SM_KnifeBot                     = (nil)                                                                 Z_mt.SM_AntiUntrusted           = (nil)
Z_mt.SM_ZeusBot                      = (nil)                                                                 Z_mt.SM_HideFromObs             = (nil)
Z_mt.SM_BlockBot                     = (nil)                                                                 Z_mt.SM_LowFpsWarning           = (nil)
Z_mt.SM_LockMenuLayout               = (nil)                                                                 Z_mt.SM_KnifeMode               = (nil)
Z_mt.SM_Zy                           = (nil)                                                                 Z_mt.SM_Zx                      = (nil)
Z_mt.SM_ADelay                       = (nil)                                                                 Z_mt.SM_PingVal                 = (nil)
Z_mt.SM_ClanTagSpammer               = (nil)                                                                 Z_mt.SM_LogDamageDealt          = (nil)
Z_mt.SM_LogPurchases                 = (nil)                                                                 Z_mt.SM_StandaloneQuickStop     = (nil)
Z_mt.SM_RevealOverwatchPlayers       = (nil)                                                                 Z_mt.SM_InfiniteDuck            = (nil)
Z_mt.SM_EasyStrafe                   = (nil)                                                                 Z_mt.SM_OverrideZoomFov         = (nil)

return Z_mt
