local Z_mt = {} -- Thanks to Aviarita for the idea of using metatable & Thanks to duk for telling me how to set/obtain color picker values properly.
---------------------------------------------------------------------------------------------------------RAGE BOT-----------------------------------------------------------------------------------------------------------------
Z_mt.R_Enabled                             = ui.reference("RAGE", "Aimbot", "Enabled")                              Z_mt.R_RemoveSpread                    = ui.reference("RAGE", "Other", "Remove spread")
Z_mt.R_TargetSelection                     = ui.reference("RAGE", "Aimbot", "Target selection")                     Z_mt.R_RemoveRecoil                    = ui.reference("RAGE", "Other", "Remove recoil")
Z_mt.R_TargetHitbox                        = ui.reference("RAGE", "Aimbot", "Target hitbox")                        Z_mt.R_AccuracyBoost                   = ui.reference("RAGE", "Other", "Accuracy boost")
Z_mt.R_AvoidLimbs                          = ui.reference("RAGE", "Aimbot", "Avoid limbs if moving")                Z_mt.R_AccuracyBoostOptions            = ui.reference("RAGE", "Other", "Accuracy boost options")
Z_mt.R_AvoidHead                           = ui.reference("RAGE", "Aimbot", "Avoid head if jumping")                Z_mt.R_QuickStop                       = ui.reference("RAGE", "Other", "Quick stop")
Z_mt.R_MultiPoint, zz, MpMode              = ui.reference("RAGE", "Aimbot", "Multi-point")                          Z_mt.R_QuickStopEarly                  = ui.reference("RAGE", "Other", "Quick stop early")
Z_mt.R_MultiPointScale                     = ui.reference("RAGE", "Aimbot", "Multi-point scale")                    Z_mt.R_QuickStopInFire                 = ui.reference("RAGE", "Other", "Quick stop in fire")
Z_mt.R_DynamicMultiPoint                   = ui.reference("RAGE", "Aimbot", "Dynamic multi-point")                  Z_mt.R_QuickPeekAssist                 = ui.reference("RAGE", "Other", "Quick peek assist")
Z_mt.R_StomachScale                        = ui.reference("RAGE", "Aimbot", "Stomach hitbox scale")                 Z_mt.R_AntiAimCorrection               = ui.reference("RAGE", "Other", "Anti-Aim correction")
Z_mt.R_AutomaticFire                       = ui.reference("RAGE", "Aimbot", "Automatic fire")                       Z_mt.R_PreferBodyAim                   = ui.reference("RAGE", "Other", "Prefer body aim")
Z_mt.R_AutomaticPenetration                = ui.reference("RAGE", "Aimbot", "Automatic penetration")                Z_mt.R_DelayShotOnUnduck               = ui.reference("RAGE", "Other", "Delay shot on unduck")
Z_mt.R_SilentAim                           = ui.reference("RAGE", "Aimbot", "Silent aim")                           Z_mt.R_DoubleTap                       = ui.reference("RAGE", "Other", "Double tap")
Z_mt.R_MinHitchance                        = ui.reference("RAGE", "Aimbot", "Minimum hit chance")                   Z_mt.R_AutomaticScope                  = ui.reference("RAGE", "Aimbot", "Automatic scope")
Z_mt.R_MinDamage                           = ui.reference("RAGE", "Aimbot", "Minimum Damage")                       Z_mt.R_ReduceAimStep                   = ui.reference("RAGE", "Aimbot", "Reduce aim step")
Z_mt.R_MaximumFov                          = ui.reference("RAGE", "Aimbot", "Maximum FOV")                          Z_mt.R_LowFpsMitigations               = ui.reference("RAGE", "Aimbot", "Low FPS mitigations")
Z_mt.R_LogMissesDueToSpread                = ui.reference("RAGE", "Aimbot", "Log misses due to spread")             Z_mt.R_OverrideAwp                     = ui.reference("RAGE", "Aimbot", "Override AWP")
---------------------------------------------------------------------------------------------------------Anti-Aim-----------------------------------------------------------------------------------------------------------------
Z_mt.A_Pitch                               = ui.reference("AA", "Anti-aimbot angles", "Pitch")                      Z_mt.A_Enabled                         = ui.reference("AA", "Fake lag", "Enabled")
Z_mt.A_YawBase                             = ui.reference("AA", "Anti-aimbot angles", "Yaw base")                   Z_mt.A_CustomizeTriggers               = ui.reference("AA", "Fake lag", "Customize triggers")
Z_mt.A_Yaw, YawSlider                      = ui.reference("AA", "Anti-aimbot angles", "Yaw")                        Z_mt.A_Triggers                        = ui.reference("AA", "Fake lag", "Triggers")
Z_mt.A_YawJitter, YawJSlider               = ui.reference("AA", "Anti-aimbot angles", "Yaw jitter")                 Z_mt.A_Amount                          = ui.reference("AA", "Fake lag", "Amount")
Z_mt.A_BodyYaw, BodyYSlider                = ui.reference("AA", "Anti-aimbot angles", "Body yaw")                   Z_mt.A_Variance                        = ui.reference("AA", "Fake lag", "Variance")
Z_mt.A_FakeYawLimit                        = ui.reference("AA", "Anti-aimbot angles", "Fake yaw limit")             Z_mt.A_Limit                           = ui.reference("AA", "Fake lag", "Limit")
Z_mt.A_EdgeYaw                             = ui.reference("AA", "Anti-aimbot angles", "Edge yaw")                   Z_mt.A_FakeLagWhileShooting            = ui.reference("AA", "Fake lag", "Fake lag while shooting")
Z_mt.A_EdgeFakeYawOffset                   = ui.reference("AA", "Anti-aimbot angles", "Edge fake yaw offset")       Z_mt.A_ResetOnBunnyHop                 = ui.reference("AA", "Fake lag", "Reset on bunny hop")
Z_mt.A_FreeStanding                        = ui.reference("AA", "Anti-aimbot angles", "Freestanding")               Z_mt.A_SlowMotion                      = ui.reference("AA", "Other", "Slow motion")
Z_mt.A_FreeStandingIgnoreDuck              = ui.reference("AA", "Anti-aimbot angles", "Freestanding ignore duck")   Z_mt.A_FixLegMovement                  = ui.reference("AA", "Other", "Fix leg movement")
Z_mt.A_FreeStandingBodyYaw                 = ui.reference("AA", "Anti-aimbot angles", "Freestanding body yaw")      Z_mt.A_InfiniteDuck                    = ui.reference("AA", "Other", "Infinite duck")
Z_mt.A_LowerBodyYaw                        = ui.reference("AA", "Anti-aimbot angles", "Lower body yaw")             Z_mt.A_OnShotAntiAim                   = ui.reference("AA", "Other", "On shot anti-aim")
Z_mt.A_SlowMotionType                      = ui.reference("AA", "Other", "Slow motion type")
---------------------------------------------------------------------------------------------------------VISUALS------------------------------------------------------------------------------------------------------------------
Z_mt.V_Teammates                           = ui.reference("VISUALS", "Player ESP", "Teammates")                     Z_mt.V_Player, Color14                 = ui.reference("VISUALS", "Colored models", "Player")
Z_mt.V_Dormant                             = ui.reference("VISUALS", "Player ESP", "Dormant")                       Z_mt.V_PBW, Color15, Typ1, Color16     = ui.reference("VISUALS", "Colored models", "Player behind wall")
Z_mt.V_BoundingBox, Color0                 = ui.reference("VISUALS", "Player ESP", "Bounding box")                  Z_mt.V_LocalFakeShadow, Color21        = ui.reference("VISUALS", "Colored models", "Local fake shadow")
Z_mt.V_HealthBar                           = ui.reference("VISUALS", "Player ESP", "Health bar")                    Z_mt.V_ShowTeammates, Color17          = ui.reference("VISUALS", "Colored models", "Show teammates")
Z_mt.V_Name, Color1                        = ui.reference("VISUALS", "Player ESP", "Name")                          Z_mt.V_Hands, Color18, Typ2, Color19   = ui.reference("VISUALS", "Colored models", "Hands")
Z_mt.V_Flags                               = ui.reference("VISUALS", "Player ESP", "Flags")                         Z_mt.V_Shadow, Color20                 = ui.reference("VISUALS", "Colored models", "Shadow")
Z_mt.V_WeaponText                          = ui.reference("VISUALS", "Player ESP", "Weapon text")                   Z_mt.V_Crosshair                       = ui.reference("VISUALS", "Other ESP", "Crosshair")
Z_mt.V_WeaponIcon, Color2                  = ui.reference("VISUALS", "Player ESP", "Weapon icon")                   Z_mt.V_DroppedWeaponAmmo               = ui.reference("VISUALS", "Other ESP", "Dropped weapon ammo")
Z_mt.V_Ammo, Color3                        = ui.reference("VISUALS", "Player ESP", "Ammo")                          Z_mt.V_Radar                           = ui.reference("VISUALS", "Other ESP", "Radar")    
Z_mt.V_Distance                            = ui.reference("VISUALS", "Player ESP", "Distance")                      Z_mt.V_DroppedWeapon, Color22          = ui.reference("VISUALS", "Other ESP", "Dropped weapons")
Z_mt.V_Glow, Color4                        = ui.reference("VISUALS", "Player ESP", "Glow")                          Z_mt.V_Grenades, Color23               = ui.reference("VISUALS", "Other ESP", "Grenades")
Z_mt.V_HitMarker                           = ui.reference("VISUALS", "Player ESP", "Hit marker")                    Z_mt.V_InaccuracyOverlay, Color24      = ui.reference("VISUALS", "Other ESP", "Inaccuracy overlay")
Z_mt.V_HitMarkerSound                      = ui.reference("VISUALS", "Player ESP", "Hit marker sound")              Z_mt.V_RecoilOverlay                   = ui.reference("VISUALS", "Other ESP", "Recoil overlay")
Z_mt.V_VisualizeSounds, Color5             = ui.reference("VISUALS", "Player ESP", "Visualize sounds")              Z_mt.V_Bomb, Color25                   = ui.reference("VISUALS", "Other ESP", "Bomb")
Z_mt.V_LineOfSight, Color6                 = ui.reference("VISUALS", "Player ESP", "Line of sight")                 Z_mt.V_GrenadeTrajectory, Color26      = ui.reference("VISUALS", "Other ESP", "Grenade trajectory")
Z_mt.V_Money                               = ui.reference("VISUALS", "Player ESP", "Money")                         Z_mt.V_GrenadeProximityWarning         = ui.reference("VISUALS", "Other ESP", "Grenade proximity warning")
Z_mt.V_Skeleton, Color7                    = ui.reference("VISUALS", "Player ESP", "Skeleton")                      Z_mt.V_Spectators                      = ui.reference("VISUALS", "Other ESP", "Spectators")
Z_mt.V_OOFA, Color8, Pos, Size             = ui.reference("VISUALS", "Player ESP", "Out of FOV arrow")              Z_mt.V_PenetrationReticle              = ui.reference("VISUALS", "Other ESP", "Penetration reticle")
Z_mt.V_RemoveFlash                         = ui.reference("VISUALS", "Effects", "Remove flashbang effects")         Z_mt.V_Hostages, Color27               = ui.reference("VISUALS", "Other ESP", "Hostages")
Z_mt.V_RemoveSmoke                         = ui.reference("VISUALS", "Effects", "Remove smoke grenades")            Z_mt.V_SharedEsp                       = ui.reference("VISUALS", "Other ESP", "Shared ESP")  
Z_mt.V_RemoveFog                           = ui.reference("VISUALS", "Effects", "Remove fog")                       Z_mt.V_SharedEspWithOtherTeam          = ui.reference("VISUALS", "Other ESP", "Shared ESP with other team")
Z_mt.V_RemoveSkybox                        = ui.reference("VISUALS", "Effects", "Remove skybox")                    Z_mt.V_RestrictSharedEspUpdates        = ui.reference("VISUALS", "Other ESP", "Restrict shared ESP updates")
Z_mt.V_VisualRecoilAdjustment              = ui.reference("VISUALS", "Effects", "Visual recoil adjustment")         Z_mt.V_UpgradeTablet                   = ui.reference("VISUALS", "Other ESP", "Upgrade tablet")
Z_mt.V_TransparentWalls                    = ui.reference("VISUALS", "Effects", "Transparent walls")                Z_mt.V_DangerZoneItems                 = ui.reference("VISUALS", "Other ESP", "Danger Zone items")
Z_mt.V_TransparentProps                    = ui.reference("VISUALS", "Effects", "Transparent props")                Z_mt.V_DroneGun, Color28               = ui.reference("VISUALS", "Other ESP", "Drone gun")
Z_mt.V_BrightnessAdjustment                = ui.reference("VISUALS", "Effects", "Brightness adjustment")            Z_mt.V_BlackHawk, Color29              = ui.reference("VISUALS", "Other ESP", "Blackhawk")
Z_mt.V_RemoveScope                         = ui.reference("VISUALS", "Effects", "Remove scope overlay")             Z_mt.V_Drone, Color30                  = ui.reference("VISUALS", "Other ESP", "Drone")
Z_mt.V_InstantScope                        = ui.reference("VISUALS", "Effects", "Instant scope")                    Z_mt.V_RandomCase, Color31             = ui.reference("VISUALS", "Other ESP", "Random case")
Z_mt.V_DisablePostProcessing               = ui.reference("VISUALS", "Effects", "Disable post processing")          Z_mt.V_ToolCase, Color32               = ui.reference("VISUALS", "Other ESP", "Tool case")
Z_mt.V_ForceThirdPersonA                   = ui.reference("VISUALS", "Effects", "Force third person (alive)")       Z_mt.V_PistolCase, Color33             = ui.reference("VISUALS", "Other ESP", "Pistol case")
Z_mt.V_ForceThirdPersonD                   = ui.reference("VISUALS", "Effects", "Force third person (dead)")        Z_mt.V_ExplosiveCase, Color34          = ui.reference("VISUALS", "Other ESP", "Explosive case")
Z_mt.V_DisableTeammates                    = ui.reference("VISUALS", "Effects", "Disable rendering of teammates")   Z_mt.V_HeavyWeaponCase, Color35        = ui.reference("VISUALS", "Other ESP", "Heavy weapon case")
Z_mt.V_BulletTracers, Color9               = ui.reference("VISUALS", "Effects", "Bullet tracers")                   Z_mt.V_LightWeaponCase, Color36        = ui.reference("VISUALS", "Other ESP", "Light weapon case")
Z_mt.V_BulletImpacts, Duration             = ui.reference("VISUALS", "Effects", "Bullet impacts")                   Z_mt.V_DuffleBag, Color37              = ui.reference("VISUALS", "Other ESP", "Dufflebag")
Z_mt.V_Jammer, Color10                     = ui.reference("VISUALS", "Other ESP", "Jammer")                         Z_mt.V_Briefcase, Color38              = ui.reference("VISUALS", "Other ESP", "Briefcase")
Z_mt.V_Ammobox, Color11                    = ui.reference("VISUALS", "Other ESP", "Ammobox")                        Z_mt.V_TabletUpgradeZone, Color39      = ui.reference("VISUALS", "Other ESP", "Tablet upgrade drone")
Z_mt.V_Armor, Color12                      = ui.reference("VISUALS", "Other ESP", "Armor")                          Z_mt.V_TabletUpgradeDrone, Color40     = ui.reference("VISUALS", "Other ESP", "Tablet upgrade zone")
Z_mt.V_ParachutePack, Color13              = ui.reference("VISUALS", "Other ESP", "Parachute pack")                 Z_mt.V_CashStack, Color41              = ui.reference("VISUALS", "Other ESP", "Cash stack")
Z_mt.V_DisableModelOcclusion               = ui.reference("VISUALS", "Colored models", "Disable model occlusion")
---------------------------------------------------------------------------------------------------------MISC TAB-----------------------------------------------------------------------------------------------------------------
Z_mt.M_OverrideFov                         = ui.reference("MISC", "Miscellaneous", "Override FOV")                  Z_mt.M_RevealCompetitiveRanks          = ui.reference("MISC", "Miscellaneous", "Reveal competitive ranks")
Z_mt.M_BunnyHop                            = ui.reference("MISC", "Miscellaneous", "Bunny hop")                     Z_mt.M_AutoAcceptMatchmaking           = ui.reference("MISC", "Miscellaneous", "Auto-accept matchmaking")
Z_mt.M_AirStrafe                           = ui.reference("MISC", "Miscellaneous", "Air strafe")                    Z_mt.M_AutomaticGrenadeRelease         = ui.reference("MISC", "Miscellaneous", "Automatic grenade release")
Z_mt.M_AirStrafeDirection                  = ui.reference("MISC", "Miscellaneous", "Air strafe direction")          Z_mt.M_PingSpike, vbx, PingVal         = ui.reference("MISC", "Miscellaneous", "Ping spike")
Z_mt.M_AirStrafeSmoothing                  = ui.reference("MISC", "Miscellaneous", "Air strafe smoothing")          Z_mt.M_FastWalk                        = ui.reference("MISC", "Miscellaneous", "Fast walk")
Z_mt.M_Zhop, xx, Zy, Zx                    = ui.reference("MISC", "Miscellaneous", "Z-Hop")                         Z_mt.M_PersistentKillFeed              = ui.reference("MISC", "Miscellaneous", "Persistent kill feed")
Z_mt.M_PreSpeed                            = ui.reference("MISC", "Miscellaneous", "Pre-speed")                     Z_mt.M_AntiUntrusted                   = ui.reference("MISC", "Settings", "Anti-untrusted")
Z_mt.M_AirDuck                             = ui.reference("MISC", "Miscellaneous", "Air duck")                      Z_mt.M_HideFromObs                     = ui.reference("MISC", "Settings", "Hide from OBS")
Z_mt.M_KnifeBot, KnifeMode                 = ui.reference("MISC", "Miscellaneous", "Knifebot")                      Z_mt.M_LowFpsWarning                   = ui.reference("MISC", "Settings", "Low FPS warning")
Z_mt.M_ZeusBot                             = ui.reference("MISC", "Miscellaneous", "Zeusbot")                       Z_mt.M_LockMenuLayout                  = ui.reference("MISC", "Settings", "Lock menu layout")
Z_mt.M_BlockBot                            = ui.reference("MISC", "Miscellaneous", "Blockbot")                      Z_mt.M_LoadConfig                      = ui.reference("MISC", "Other", "Load config")
Z_mt.M_AutomaticWeapons, ADelay            = ui.reference("MISC", "Miscellaneous", "Automatic weapons")             Z_mt.M_ResetConfig                     = ui.reference("MISC", "Other", "Reset config")
Z_mt.M_JumpAtEdge                          = ui.reference("MISC", "Miscellaneous", "Jump at edge")                  Z_mt.M_ExportToClipBoard               = ui.reference("MISC", "Other", "Export to clipboard")
Z_mt.M_ClanTagSpammer                      = ui.reference("MISC", "Miscellaneous", "Clan tag spammer")              Z_mt.M_LogPurchases                    = ui.reference("MISC", "Miscellaneous", "Log weapon purchases")
Z_mt.M_LogDamageDealt                      = ui.reference("MISC", "Miscellaneous", "Log damage dealt")
---------------------------------------------------------------------------------------------------------STORED RAGE--------------------------------------------------------------------------------------------------------------
Z_mt.Stored_R_Enabled                      = (nil)                                                                  Z_mt.Stored_R_RemoveSpread             = (nil)
Z_mt.Stored_R_TargetSelection              = (nil)                                                                  Z_mt.Stored_R_RemoveRecoil             = (nil)
Z_mt.Stored_R_TargetHitbox                 = (nil)                                                                  Z_mt.Stored_R_AccuracyBoost            = (nil)
Z_mt.Stored_R_AvoidLimbs                   = (nil)                                                                  Z_mt.Stored_R_AccuracyBoostOptions     = (nil)
Z_mt.Stored_R_AvoidHead                    = (nil)                                                                  Z_mt.Stored_R_QuickStop                = (nil)
Z_mt.Stored_R_MultiPoint, zz, Z_mt.MpMode  = (nil)                                                                  Z_mt.Stored_R_QuickStopEarly           = (nil)
Z_mt.Stored_R_MultiPointScale              = (nil)                                                                  Z_mt.Stored_R_QuickStopInFire          = (nil)
Z_mt.Stored_R_DynamicMultiPoint            = (nil)                                                                  Z_mt.Stored_R_QuickPeekAssist          = (nil)
Z_mt.Stored_R_StomachScale                 = (nil)                                                                  Z_mt.Stored_R_AntiAimCorrection        = (nil)
Z_mt.Stored_R_AutomaticFire                = (nil)                                                                  Z_mt.Stored_R_PreferBodyAim            = (nil)
Z_mt.Stored_R_AutomaticPenetration         = (nil)                                                                  Z_mt.Stored_R_DelayShotOnUnduck        = (nil)
Z_mt.Stored_R_SilentAim                    = (nil)                                                                  Z_mt.Stored_R_OverrideAwp              = (nil)
Z_mt.Stored_R_MinHitchance                 = (nil)                                                                  Z_mt.Stored_R_AutomaticScope           = (nil)
Z_mt.Stored_R_MinDamage                    = (nil)                                                                  Z_mt.Stored_R_ReduceAimStep            = (nil)
Z_mt.Stored_R_MaximumFov                   = (nil)                                                                  Z_mt.Stored_R_LowFpsMitigations        = (nil)
Z_mt.Stored_R_LogMissesDueToSpread         = (nil)                                                                  Z_mt.Stored_R_MpMode                   = (nil)
Z_mt.Stored_R_DoubleTap                    = (nil)
---------------------------------------------------------------------------------------------------------STORED AA----------------------------------------------------------------------------------------------------------------
Z_mt.Stored_A_Pitch                        = (nil)                                                                  Z_mt.Stored_A_Enabled                  = (nil)
Z_mt.Stored_A_YawBase                      = (nil)                                                                  Z_mt.Stored_A_CustomizeTriggers        = (nil)
Z_mt.Stored_A_Yaw                          = (nil)                                                                  Z_mt.Stored_A_Triggers                 = (nil)
Z_mt.Stored_A_YawJitter                    = (nil)                                                                  Z_mt.Stored_A_OnShotAntiAim            = (nil)
Z_mt.Stored_A_BodyYaw                      = (nil)                                                                  Z_mt.Stored_A_Amount                   = (nil)
Z_mt.Stored_A_FakeYawLimit                 = (nil)                                                                  Z_mt.Stored_A_Variance                 = (nil)
Z_mt.Stored_A_EdgeYaw                      = (nil)                                                                  Z_mt.Stored_A_Limit                    = (nil)
Z_mt.Stored_A_EdgeFakeYawOffset            = (nil)                                                                  Z_mt.Stored_A_FakeLagWhileShooting     = (nil)
Z_mt.Stored_A_FreeStanding                 = (nil)                                                                  Z_mt.Stored_A_ResetOnBunnyHop          = (nil)
Z_mt.Stored_A_FreeStandingIgnoreDuck       = (nil)                                                                  Z_mt.Stored_A_SlowMotion               = (nil)
Z_mt.Stored_A_FreeStandingBodyYaw          = (nil)                                                                  Z_mt.Stored_A_FixLegMovement           = (nil)
Z_mt.Stored_A_LowerBodyYaw                 = (nil)                                                                  Z_mt.Stored_A_InfiniteDuck             = (nil)
Z_mt.Stored_A_YawJSlider                   = (nil)                                                                  Z_mt.Stored_A_BodyYSlider              = (nil)
Z_mt.Stored_A_YawSlider                    = (nil)                                                                  Z_mt.Stored_A_SlowMotionType           = (nil)
---------------------------------------------------------------------------------------------------------STORED VISUALS-----------------------------------------------------------------------------------------------------------
Z_mt.Stored_V_Teammates                    = (nil)                                                                  Z_mt.Stored_V_Player                   = (nil)
Z_mt.Stored_V_Dormant                      = (nil)                                                                  Z_mt.Stored_V_PBW                      = (nil)
Z_mt.Stored_V_HealthBar                    = (nil)                                                                  Z_mt.Stored_V_ShowTeammates            = (nil)
Z_mt.Stored_V_Name                         = (nil)                                                                  Z_mt.Stored_V_Hands                    = (nil)
Z_mt.Stored_V_Flags                        = (nil)                                                                  Z_mt.Stored_V_DisableModelOcclusion    = (nil)
Z_mt.Stored_V_WeaponText                   = (nil)                                                                  Z_mt.Stored_V_Shadow                   = (nil)
Z_mt.Stored_V_WeaponIcon                   = (nil)                                                                  Z_mt.Stored_V_LocalFakeShadow          = (nil)
Z_mt.Stored_V_Ammo                         = (nil)                                                                  Z_mt.Stored_V_Radar                    = (nil)    
Z_mt.Stored_V_Distance                     = (nil)                                                                  Z_mt.Stored_V_DroppedWeapon            = (nil)
Z_mt.Stored_V_Glow                         = (nil)                                                                  Z_mt.Stored_V_Grenades                 = (nil)
Z_mt.Stored_V_HitMarker                    = (nil)                                                                  Z_mt.Stored_V_InaccuracyOverlay        = (nil)
Z_mt.Stored_V_HitMarkerSound               = (nil)                                                                  Z_mt.Stored_V_RecoilOverlay            = (nil)
Z_mt.Stored_V_VisualizeSounds              = (nil)                                                                  Z_mt.Stored_V_Bomb                     = (nil)
Z_mt.Stored_V_LineOfSight                  = (nil)                                                                  Z_mt.Stored_V_GrenadeTrajectory        = (nil)
Z_mt.Stored_V_Money                        = (nil)                                                                  Z_mt.Stored_V_GrenadeProximityWarning  = (nil)
Z_mt.Stored_V_Skeleton                     = (nil)                                                                  Z_mt.Stored_V_Spectators               = (nil)
Z_mt.Stored_V_OOFA                         = (nil)                                                                  Z_mt.Stored_V_PenetrationReticle       = (nil)
Z_mt.Stored_V_RemoveFlash                  = (nil)                                                                  Z_mt.Stored_V_Hostages                 = (nil)
Z_mt.Stored_V_RemoveSmoke                  = (nil)                                                                  Z_mt.Stored_V_SharedEsp                = (nil)  
Z_mt.Stored_V_RemoveFog                    = (nil)                                                                  Z_mt.Stored_V_SharedEspWithOtherTeam   = (nil)
Z_mt.Stored_V_RemoveSkybox                 = (nil)                                                                  Z_mt.Stored_V_RestrictSharedEspUpdates = (nil)
Z_mt.Stored_V_VisualRecoilAdjustment       = (nil)                                                                  Z_mt.Stored_V_UpgradeTablet            = (nil)
Z_mt.Stored_V_TransparentWalls             = (nil)                                                                  Z_mt.Stored_V_DangerZoneItems          = (nil)
Z_mt.Stored_V_TransparentProps             = (nil)                                                                  Z_mt.Stored_V_DroneGun                 = (nil)
Z_mt.Stored_V_BrightnessAdjustment         = (nil)                                                                  Z_mt.Stored_V_BlackHawk                = (nil)
Z_mt.Stored_V_RemoveScope                  = (nil)                                                                  Z_mt.Stored_V_Drone                    = (nil)
Z_mt.Stored_V_InstantScope                 = (nil)                                                                  Z_mt.Stored_V_RandomCase               = (nil)
Z_mt.Stored_V_DisablePostProcessing        = (nil)                                                                  Z_mt.Stored_V_ToolCase                 = (nil)
Z_mt.Stored_V_ForceThirdPersonA            = (nil)                                                                  Z_mt.Stored_V_PistolCase               = (nil)
Z_mt.Stored_V_ForceThirdPersonD            = (nil)                                                                  Z_mt.Stored_V_ExplosiveCase            = (nil)
Z_mt.Stored_V_DisableTeammates             = (nil)                                                                  Z_mt.Stored_V_HeavyWeaponCase          = (nil)
Z_mt.Stored_V_BulletTracers                = (nil)                                                                  Z_mt.Stored_V_LightWeaponCase          = (nil)
Z_mt.Stored_V_BulletImpacts                = (nil)                                                                  Z_mt.Stored_V_DuffleBag                = (nil)
Z_mt.Stored_V_Jammer                       = (nil)                                                                  Z_mt.Stored_V_Briefcase                = (nil)
Z_mt.Stored_V_Ammobox                      = (nil)                                                                  Z_mt.Stored_V_TabletUpgradeZone        = (nil)
Z_mt.Stored_V_Armor                        = (nil)                                                                  Z_mt.Stored_V_TabletUpgradeDrone       = (nil)
Z_mt.Stored_V_ParachutePack                = (nil)                                                                  Z_mt.Stored_V_CashStack                = (nil)
Z_mt.Stored_V_BoundingBox                  = (nil)                                                                  Z_mt.Stored_V_DroppedWeaponAmmo        = (nil)
Z_mt.Stored_V_Crosshair                    = (nil)

Z_mt.Stored_Size    = (nil)   Z_mt.Stored_Pos     = (nil)   Z_mt.Stored_Duration= (nil)   Z_mt.Stored_Typ1    = (nil)   Z_mt.Stored_Typ2    = (nil)
Z_mt.R0  = (nil)   Z_mt.R1  = (nil)   Z_mt.R2  = (nil)   Z_mt.R3  = (nil)  Z_mt.R4  = (nil)   Z_mt.R5  = (nil)   Z_mt.R6  = (nil)   Z_mt.R7  = (nil)   Z_mt.R8  = (nil)
Z_mt.R9  = (nil)   Z_mt.R10 = (nil)   Z_mt.R11 = (nil)   Z_mt.R12 = (nil)  Z_mt.R13 = (nil)   Z_mt.R14 = (nil)   Z_mt.R15 = (nil)   Z_mt.R16 = (nil)                     
Z_mt.R17 = (nil)   Z_mt.R18 = (nil)   Z_mt.R19 = (nil)   Z_mt.R20 = (nil)  Z_mt.R21 = (nil)   Z_mt.R22 = (nil)   Z_mt.R23 = (nil)   Z_mt.R24 = (nil) 
Z_mt.R25 = (nil)   Z_mt.R26 = (nil)   Z_mt.R27 = (nil)   Z_mt.R28 = (nil)  Z_mt.R29 = (nil)   Z_mt.R30 = (nil)   Z_mt.R31 = (nil)   Z_mt.R32 = (nil) 
Z_mt.R33 = (nil)   Z_mt.R34 = (nil)   Z_mt.R35 = (nil)   Z_mt.R36 = (nil)  Z_mt.R37 = (nil)   Z_mt.R38 = (nil)   Z_mt.R39 = (nil)   Z_mt.R40 = (nil)   Z_mt._R41 = (nil)
Z_mt.G0  = (nil)   Z_mt.G1  = (nil)   Z_mt.G2  = (nil)   Z_mt.G3  = (nil)  Z_mt.G4  = (nil)   Z_mt.G5  = (nil)   Z_mt.G6  = (nil)   Z_mt.G7  = (nil)   Z_mt.G8   = (nil)
Z_mt.G9  = (nil)   Z_mt.G10 = (nil)   Z_mt.G11 = (nil)   Z_mt.G12 = (nil)  Z_mt.G13 = (nil)   Z_mt.G14 = (nil)   Z_mt.G15 = (nil)   Z_mt.G16 = (nil) 
Z_mt.G17 = (nil)   Z_mt.G18 = (nil)   Z_mt.G19 = (nil)   Z_mt.G20 = (nil)  Z_mt.G21 = (nil)   Z_mt.G22 = (nil)   Z_mt.G23 = (nil)   Z_mt.G24 = (nil) 
Z_mt.G25 = (nil)   Z_mt.G26 = (nil)   Z_mt.G27 = (nil)   Z_mt.G28 = (nil)  Z_mt.G29 = (nil)   Z_mt.G30 = (nil)   Z_mt.G31 = (nil)   Z_mt.G32 = (nil) 
Z_mt.G33 = (nil)   Z_mt.G34 = (nil)   Z_mt.G35 = (nil)   Z_mt.G36 = (nil)  Z_mt.G37 = (nil)   Z_mt.G38 = (nil)   Z_mt.G39 = (nil)   Z_mt.G40 = (nil)   Z_mt._G41 = (nil)
Z_mt.B0  = (nil)   Z_mt.B1  = (nil)   Z_mt.B2  = (nil)   Z_mt.B3  = (nil)  Z_mt.B4  = (nil)   Z_mt.B5  = (nil)   Z_mt.B6  = (nil)   Z_mt.B7  = (nil)   Z_mt.B8   = (nil)
Z_mt.B9  = (nil)   Z_mt.B10 = (nil)   Z_mt.B11 = (nil)   Z_mt.B12 = (nil)  Z_mt.B13 = (nil)   Z_mt.B14 = (nil)   Z_mt.B15 = (nil)   Z_mt.B16 = (nil) 
Z_mt.B17 = (nil)   Z_mt.B18 = (nil)   Z_mt.B19 = (nil)   Z_mt.B20 = (nil)  Z_mt.B21 = (nil)   Z_mt.B22 = (nil)   Z_mt.B23 = (nil)   Z_mt.B24 = (nil) 
Z_mt.B25 = (nil)   Z_mt.B26 = (nil)   Z_mt.B27 = (nil)   Z_mt.B28 = (nil)  Z_mt.B29 = (nil)   Z_mt.B30 = (nil)   Z_mt.B31 = (nil)   Z_mt.B32 = (nil) 
Z_mt.B33 = (nil)   Z_mt.B34 = (nil)   Z_mt.B35 = (nil)   Z_mt.B36 = (nil)  Z_mt.B37 = (nil)   Z_mt.B38 = (nil)   Z_mt.B39 = (nil)   Z_mt.B40 = (nil)   Z_mt._B41 = (nil)
Z_mt.A0  = (nil)   Z_mt.A1  = (nil)   Z_mt.A2  = (nil)   Z_mt.A3  = (nil)  Z_mt.A4  = (nil)   Z_mt.A5  = (nil)   Z_mt.A6  = (nil)   Z_mt.A7  = (nil)   Z_mt.A8   = (nil)
Z_mt.A9  = (nil)   Z_mt.A10 = (nil)   Z_mt.A11 = (nil)   Z_mt.A12 = (nil)  Z_mt.A13 = (nil)   Z_mt.A14 = (nil)   Z_mt.A15 = (nil)   Z_mt.A16 = (nil) 
Z_mt.A17 = (nil)   Z_mt.A18 = (nil)   Z_mt.A19 = (nil)   Z_mt.A20 = (nil)  Z_mt.A21 = (nil)   Z_mt.A22 = (nil)   Z_mt.A23 = (nil)   Z_mt.A24 = (nil) 
Z_mt.A25 = (nil)   Z_mt.A26 = (nil)   Z_mt.A27 = (nil)   Z_mt.A28 = (nil)  Z_mt.A29 = (nil)   Z_mt.A30 = (nil)   Z_mt.A31 = (nil)   Z_mt.A32 = (nil) 
Z_mt.A33 = (nil)   Z_mt.A34 = (nil)   Z_mt.A35 = (nil)   Z_mt.A36 = (nil)  Z_mt.A37 = (nil)   Z_mt.A38 = (nil)   Z_mt.A39 = (nil)   Z_mt.A40 = (nil)   Z_mt._A41 = (nil)
---------------------------------------------------------------------------------------------------------STORED MISC--------------------------------------------------------------------------------------------------------------
Z_mt.Stored_M_OverrideFov                  = (nil)                                                                  Z_mt.Stored_M_AutomaticWeapons         = (nil)
Z_mt.Stored_M_BunnyHop                     = (nil)                                                                  Z_mt.Stored_M_JumpAtEdge               = (nil)
Z_mt.Stored_M_AirStrafe                    = (nil)                                                                  Z_mt.Stored_M_RevealCompetitveRanks    = (nil)
Z_mt.Stored_M_AirStrafeDirection           = (nil)                                                                  Z_mt.Stored_M_AutoAcceptMatchmaking    = (nil)
Z_mt.Stored_M_AirStrafeSmoothing           = (nil)                                                                  Z_mt.Stored_M_AutomaticGrenadeRelease  = (nil)
Z_mt.Stored_M_Zhop                         = (nil)                                                                  Z_mt.Stored_M_PingSpike                = (nil)
Z_mt.Stored_M_PreSpeed                     = (nil)                                                                  Z_mt.Stored_M_FastWalk                 = (nil)
Z_mt.Stored_M_AirDuck                      = (nil)                                                                  Z_mt.Stored_M_PersistentKillFeed       = (nil)   
Z_mt.Stored_M_KnifeBot                     = (nil)                                                                  Z_mt.Stored_M_AntiUntrusted            = (nil)                                                     
Z_mt.Stored_M_ZeusBot                      = (nil)                                                                  Z_mt.Stored_M_HideFromObs              = (nil)
Z_mt.Stored_M_BlockBot                     = (nil)                                                                  Z_mt.Stored_M_LowFpsWarning            = (nil)
Z_mt.Stored_M_LockMenuLayout               = (nil)                                                                  Z_mt.Stored_M_KnifeMode                = (nil) 
Z_mt.Stored_M_Zy                           = (nil)                                                                  Z_mt.Stored_M_Zx                       = (nil)
Z_mt.Stored_M_ADelay                       = (nil)                                                                  Z_mt.Stored_M_PingVal                  = (nil)
Z_mt.Stored_M_ClanTagSpammer               = (nil)                                                                  Z_mt.Stored_M_LogDamageDealt           = (nil)
Z_mt.Stored_M_LogPurchases                 = (nil)

return Z_mt -- at the end of the file
